### ISSUE TITLE
Not working in ObjC project

### ISSUE THREAD

**Issue by jhuerta88** [raulriera/TextFieldEffects#106]
Hi, My project is in Objective-C, I copied the TextFieldEffects folder in my project and deleted the TextFieldEffects.h file. 

I don't know what am I doing wrong but I'm getting this kind of errors (see image) in every function in every class. I already have another Swift Library successfully working in this project.

I'm using Xcode 8 in macOS Sierra.
<img width="1148" alt="screen shot 2016-10-12 at 18 37 03" src="https://cloud.githubusercontent.com/assets/1843776/19331559/f1e9428c-90aa-11e6-9ab3-2475218eded9.png">

**Comment by raulriera** [comment]
Hi, Is your project setup for swift 3?

**Comment by jhuerta88** [comment]
The other swift code I have is not completely in Swft 3, but I made your code into a Framework, and now its working fine. Thanks for your answer.

**Comment by jhuerta88** [comment]
Everything was working fine, but suddenly the IBInspectables stopped working, I thought is because this http://www.openradar.me/21258097, so I deleted the Framework and copy the TextField folder in the project (I already updated the other Swift code), and now it builds, but IBInspectables still not working.

**Comment by raulriera** [comment]
Hi, I am going to need a test project to test this, since this is working in the demo project included with this library

**Comment by jhuerta88** [comment]
Hi, 
I did what this answer recommends (http://stackoverflow.com/questions/26656400/uibutton-with-ib-designable-throws-runtime-attribute-warning-and-does-not-render) but it didn't work the first time, so I delete TextFieldEffects folder, all references in IB and classes and then did the cleaning procedure again. Then I copied again TextFieldEffects folder and when in IB set a TextField class to one of yours, then it worked. 

I have a final doubt: if I want to access a property from Objective-C do I need to add @objc to every one of them in every class?

**Comment by raulriera** [comment]
What do you mean by access a property? Most of the properties are available in objective-c as well. Expect the animation closures I believe.

**Comment by jhuerta88** [comment]
I meant for editing in code from my ObjC class (To be accessible and usable in Objective-C, a Swift class must be a descendant of an Objective-C class or it must be marked @objc.), but I see they're working, is it because of the "open" modifier?

**Comment by raulriera** [comment]
It's because they are UITextField, that class is an NSObject. I'm closing this as you found out the fix. We can still chat about the implementation if you like

**Comment by jhuerta88** [comment]
I'm still learning about Swift, thanks for your patience.

**Comment by raulriera** [comment]
You made the right choice 😂  Kidding aside, Swift is great. You are going to love it
