### ISSUE TITLE
Swift 3.0 support [Already supported, read for more info]

### ISSUE THREAD

**Issue by ogezue** [raulriera/TextFieldEffects#111]
Is there Swift 3.0 support?

**Comment by raulriera** [comment]
Yes, master and the latest release is swift 3.0

**Comment by sgonzalesallan** [comment]
Latest release was `1.3.0` and still xcode asking me to convert it to convert the code to swift 3. What am i missing here? thanks.

**Comment by raulriera** [comment]
Are you sure you have everything setup correctly on your project? if you download the repo and run it on Xcode 8.2 (screenshot) there are warnings about Swift 3, it wouldn't even compile if the code wasn't Swift 3

![screen shot 2016-12-13 at 11 15 20](https://cloud.githubusercontent.com/assets/24159/21148198/761d3572-c125-11e6-9468-60e068fb4909.png)

**Comment by sgonzalesallan** [comment]
Exactly what've encountered. Updating cocoapods fixed the issue in using pods. Thanks!

`gem install cocoapods`
