### ISSUE TITLE
Make different font size 

### ISSUE THREAD

**Issue by ahmadabudawod** [raulriera/TextFieldEffects#113]
I want to make different font size and color when start writing inside textfield.

**Comment by raulriera** [comment]
Have you looked at the properties you can override?

**Comment by ahmadabudawod** [comment]
Ok but it is only number , can't select font family and font size

**Comment by raulriera** [comment]
I don't get your question then. The textfield uses the fontsize, color and family that you specify normally using the iOS SDK

**Comment by raulriera** [comment]
And then use  the properties in this library's API to change the placeholder

**Comment by ahmadabudawod** [comment]
What i mean i want the textfield before enter any text big text , but after i start writing it will go up and i need to small rather than keep it with same size  before start writing in Textfield.

**Comment by raulriera** [comment]
> What i mean i want the textfield before enter any text big text , but after i start writing it will go up and i need to small rather than keep it with same size before start writing in Textfield.

Sorry, I don't understand that message

**Comment by ahmadabudawod** [comment]
See this library below , it will clear my question .
https://github.com/ArtSabintsev/UIFloatLabelTextField

**Comment by raulriera** [comment]
I see. There are no plans to add support for more effects though

**Comment by ahmadabudawod** [comment]
Thanks ,
