### ISSUE TITLE
Textfield effect crash Xcode with my Animations

### ISSUE THREAD

**Issue by ewan34500** [raulriera/TextFieldEffects#115]
Hello,

When I try to use xcode since I imported my custom class ( generated with QuartzCode ) Xcode crash during signin process.
I try to delete your pod , but the error is steal here. ( I can see in xcode : Designables : Update )
How can I resolve this issue ?

**Comment by raulriera** [comment]
Hi,

This doesn't sounds like something related to this library if you removed it and you are still having problems. You could try providing more detail and using sites like stackoverflow.com to debug the issue
