### ISSUE TITLE
Added TextField with error label 

### ISSUE THREAD

**Issue by ajaytothenew** [raulriera/TextFieldEffects#116]
This seems to be an awesome component. But using this library, how can I achieve below error message label ? 
i.e. TextField Title, TextField and an Error label

![screen shot 2017-03-01 at 11 07 24 am](https://cloud.githubusercontent.com/assets/22211843/23447248/9a6522c8-fe6f-11e6-87a4-6418c1fb3f87.png)

**Comment by raulriera** [comment]
Hi,

You can't. You will need to extend the library to allow error messages like that. Or just add labels below the text fields and show and hide them at will
