### ISSUE TITLE
HoshiTextField fades out to 0.5 after animation

### ISSUE THREAD

**Issue by praveenambekar** [raulriera/TextFieldEffects#118]
Hi,

I'm using HoshiTextField for my login screen. Is there any way to configure fontsize of placeholder? Appreciate early response.

Thanks!

**Comment by raulriera** [comment]
Hi,

All effects have a property called placeholderFontScale, which will do what you want. It's only percentage based on the font of the textfield. But it would work for most cases

```
/**
     The scale of the placeholder font.
     
     This property determines the size of the placeholder label relative to the font size of the text field.
    */
    @IBInspectable dynamic open var placeholderFontScale: CGFloat = 0.65 {
        didSet {
            updatePlaceholder()
        }
    }
```

**Comment by praveenambekar** [comment]
Thanks for your reply.

I have used placeholderFontScale to set the font of placeholder font size. How ever the font color looks faded. Actually my font is Red Color. after setting placeholderFontScale it's faded and looks like its alpha is changed. Is there any way that i can maintain color with same effect.

Thanks!

**Comment by raulriera** [comment]
can you post a screenshot of the issue? (100% simulator size, no scaling)

**Comment by praveenambekar** [comment]
@raulriera , PFA. Thanks!
![screen shot 2017-03-23 at 10 47 18 am](https://cloud.githubusercontent.com/assets/1011186/24233118/344c5e68-0fb6-11e7-8d1d-01a55d55a130.png)
![screen shot 2017-03-23 at 10 47 37 am](https://cloud.githubusercontent.com/assets/1011186/24233127/47c20998-0fb6-11e7-91ac-13b26d2145cf.png)

**Comment by raulriera** [comment]
Oh ok, I see what you mean. That is how the effect works, but it seems to be something I made up. This is not how Hoshi in the website looks like. Maybe they changed it. The culprit line is https://github.com/raulriera/TextFieldEffects/blob/master/TextFieldEffects/TextFieldEffects/HoshiTextField.swift#L109

**Comment by praveenambekar** [comment]
@raulriera , What is the Solution for this? How to proceed further?

**Comment by raulriera** [comment]
A pull request with the changes would go a long way :)

**Comment by praveenambekar** [comment]
@raulriera , Have you committed something. i don't see any new changes. Appreciate your help!
