### ISSUE TITLE
Implement intrinsicContentSize

### ISSUE THREAD

**Issue by olejnjak** [raulriera/TextFieldEffects#121]
Hi, would it be possible to implement `intrinsicContentSize` so textfields work with autolayout without adding height constraint? Or is it unimplemented by design?

**Comment by raulriera** [comment]
Given just how precise some of the effects are. Everything was done without using auto layout. But I would totally accept PRs to improve it

**Comment by olejnjak** [comment]
Okay thanks, I'll think about it and eventually create PR :-)
