### ISSUE TITLE
Error Within Outlets - Akira Text Field

### ISSUE THREAD

**Issue by deborahelizabethpadilla** [raulriera/TextFieldEffects#122]
Hi there!

I'm receiving an error within my outlets for Akira Text Field. My other view controller works fine when connecting and using the framework. The class and module are connected also. Not sure why this is happening in one view controller but not the other.

Thanks in advance.

**Comment by deborahelizabethpadilla** [comment]
Hey Raul. Below is a screenshot. Hope this clarifies. I have the same setup in a different view controller and its working fine. So not sure what's going on.

![screen shot 2017-04-05 at 11 07 36 am](https://cloud.githubusercontent.com/assets/20284373/24712262/610d3780-19f0-11e7-97eb-2ec85da627e5.png)

**Comment by raulriera** [comment]
You don't seem to be doing `import TextFieldEffects` in that View Controller

**Comment by deborahelizabethpadilla** [comment]
Hm. That's strange because I didn't import TextFieldEffects in the other view controller. Whenever I did that? I would receive an error that was 'no such module', but when I left it alone in the custom class it worked fine.

**Comment by raulriera** [comment]
Are you not using it as a library or cocoa pods? Also, what is the error that Xcode is telling you?

**Comment by deborahelizabethpadilla** [comment]
"Use Of Undeclared Type Akira TextField" is what its giving me. I'm using CocoaPods.

**Comment by raulriera** [comment]
I see, can't think of anything out the top of my head right now without looking at the project. :|

**Comment by deborahelizabethpadilla** [comment]
Really strange! Thanks for your help. If I figure out the solution, I will come back to post. I'm going to try a few things. Thanks!

**Comment by deborahelizabethpadilla** [comment]
Hey! Wanted to follow up with my answer. I restarted my project a few times and imported TextFieldEffects in my swift file. I still did not import it in my other view controller and it works, so I'm not sure why this is happening. The error went away now though, so if someone is struggling with a similar issue hopefully this helps.

**Comment by raulriera** [comment]
Glad you worked it out!

**Comment by ranahaani** [comment]
facing same issue, tried all solutions, but still facing error
