### ISSUE TITLE
Xcode 8.3

### ISSUE THREAD

**Issue by jhaque95** [raulriera/TextFieldEffects#123]
Is it still compatible with the new 8.3 update? When I tried building it, I got many errors.

**Comment by raulriera** [comment]
It is. If you download the sample project what errors do you get?

**Comment by jhaque95** [comment]
![screenshot 2017-04-22 13 40 20](https://cloud.githubusercontent.com/assets/18504218/25307128/659cbe50-2761-11e7-80f0-56c4f379180a.png)
These are the types of error I am getting. When every I try to let xcode fix it, it says the code is 'locked.'

**Comment by jhaque95** [comment]
This problem happens when I tried to integrate the workspace into my personal project I am trying. I have no errors when I use the sample project.

**Comment by raulriera** [comment]
Are you sure your personal project uses Swift 3? Or that you are using the latests version of this library?

**Comment by jhaque95** [comment]
I used cocoa pods to install the workspace, I followed the instructions on the GitHub account. The problem I am having it looks like is that the latest library is not being used.

**Comment by raulriera** [comment]
I can't help you if you don't provide any info... example project with the error, pod file, anything?

**Comment by jhaque95** [comment]
I apologize for being so vague, I have resolved the issue by following the 'Manual' instructions (Dragging and dropping in the 'TextFieldEffects' folder into my workspace).

**Comment by raulriera** [comment]
Glad it worked out!
