### ISSUE TITLE
 IB Designables: Ignoring user defined runtime attribute for key path 

### ISSUE THREAD

**Issue by XOneto9** [raulriera/TextFieldEffects#127]
Hi, I'm David

In recently I was updating TextFieldEffects 1.3.2 to 1.3.3

Unfortunately, I have a lot of issue 
like this..

`Main.storyboard: warning: IB Designables: Ignoring user defined runtime attribute for key path "borderActiveColor" on instance of "UITextField". Hit an exception when attempting to set its value: [<UITextField 0x7fb421558e00> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key borderActiveColor.`

besides above like this message, I have more run time issue.
....
in temporally, I want to go back to downgrade version of 1.3.2
how can I do that???........

**Comment by raulriera** [comment]
> in temporally, I want to go back to downgrade version of 1.3.2
how can I do that???........

Depends on how you installed it

**Comment by XOneto9** [comment]
@raulriera 
Hi,

now my TextEffects version is 1.3.3
I wish 1.3.2v is it possible?

**Comment by raulriera** [comment]
I don't understand the question, you can revert to 1.3.2 without any issues

**Comment by XOneto9** [comment]
@raulriera 
Thanks

Ok, exactly, I don't know how to do to revert 1.3.2
until now, I have known the way to choice version using with '~> 1.3.2' on cocoa pods .
isn't it?
several times I try like this
pod 'TextFieldEffects', '~> 1.3.2'

but every time install 1.3.3

that is reason why I ask basically

**Comment by raulriera** [comment]
Something like this? https://stackoverflow.com/questions/16758253/cocoapods-use-specific-pod-version

**Comment by khandkashivam** [comment]
text fields not animating in latest swift...
like in hoshiTextFieldEffect, while editing text field the placeholder doesnt goes up, but after ending the edit.. then the placeholder text goes up..help me
