### ISSUE TITLE
Text from ViewDidLoad disappears on touching TextField

### ISSUE THREAD

**Issue by boa00** [raulriera/TextFieldEffects#132]
I have some pre-existing text for TextFields in my ViewController: 

```
 @IBOutlet weak var word: UITextField!
 @IBOutlet weak var translation: UITextField!
 @IBOutlet weak var exOne: UITextField!
 @IBOutlet weak var exTwo: UITextField!

override func viewDidLoad() {
        super.viewDidLoad()
        
        // set text for textFields from the Firebase
        word.text = wo
        translation.text = tran
        exOne.text = eO
        exTwo.text = eT
}
```
I attached MadokaTextField to all my TextFields (problem appears on any type). Everything loads fine, until I press on any of this TextFields, then text inside them disappears once and for all. How can I solve this issue? Thanks!

**Comment by raulriera** [comment]
Make sure that your fields have enough height to support the layout you want. Try checking out the example project

**Comment by boa00** [comment]
Well, I implemented the same heigh for the TextField inside TableViewCell, as it is presented in the example project, and it works. But only inside this Cell. I can't figure out how to achieve outside the Cell... Is there any special requirements for constraints which I don't catch?

**Comment by raulriera** [comment]
Can't help you out if I don't see what you are doing. Try setting up a height constraint to make it big enough so that the textfield can show all your info

**Comment by boa00** [comment]
Basically, I've forgotten to uncheck "Clear when editing begins". Sorry, my fault

**Comment by raulriera** [comment]
Glad you worked it out :)
