### ISSUE TITLE
iOS 11 Yoshiko not showing text while editing?

### ISSUE THREAD

**Issue by theappedia** [raulriera/TextFieldEffects#133]
Was working all fine on 10.3, however on devices running iOS 11 Yoshiko textfield is not showing text while it is being edited, as soon as the textfield ends editing, whatever text is typed shows up correctly, please help thanks.

**Comment by raulriera** [comment]
It seems that all the layer positions changed in iOS 11... using `insertLayer(borderLayer, at: 0)` will make the problem go away. I will debug it longer and push an update when I have time. For the meanwhile you can make those changes locally in your code

Thanks for the report

**Comment by theappedia** [comment]
Hi, thanks for the response, however I am unsure where exactly I need to use `insertLayer(borderLayer, at: 0)`. All the places I've tried give me an error > Type 'YoshikoTextField' has no member 'insertLayer'
I am a bit of a beginner with coding to be honest. Any help is much appreciated, cheers!

**Comment by willyaako** [comment]
Same problem. Is there any other solution? Thanks~

**Comment by raulriera** [comment]
Updating the effect is the only solution. Apple made internal changes. I recommend doing the fix I mentioned while I try to find a fix for all of them. PR welcomes

**Comment by codenameDuchess** [comment]
This was the change needed in JiroTextField.swift .... line 69

    override open func drawViewsForRect(_ rect: CGRect) {
        let frame = CGRect(origin: CGPoint.zero, size: CGSize(width: rect.size.width, height: rect.size.height))
        
        placeholderLabel.frame = frame.insetBy(dx: placeholderInsets.x, dy: placeholderInsets.y)
        placeholderLabel.font = placeholderFontFromFont(font!)
        
        updateBorder()
        updatePlaceholder()
        
//        layer.addSublayer(borderLayer)
        layer.insertSublayer(borderLayer, at: 0)
        addSubview(placeholderLabel)        
    }

**Comment by raulriera** [comment]
Pushed some changes to master, until all the effects are fixed I can't release a new version https://github.com/raulriera/TextFieldEffects/commit/f7df6ce3f8232faf4ec5778fde1a6a0f537cd6b7 note that Apple changed the way drawRect works in iOS 11 and now it gets called when a TextField becomes first responding, causing some effects to "animate twice" and break

**Comment by raulriera** [comment]
Fixed in https://github.com/raulriera/TextFieldEffects/releases/tag/1.4.0

**Comment by Karthikeyanbhc-33** [comment]
Hi,  I need to get the selected yoshiko textfield. I can able to do this by delegating it, but its not getting any input from the keyboard. I tried with your last commit also.

**Comment by raulriera** [comment]
Does the example project work for you?

**Comment by Karthikeyanbhc-33** [comment]
I tried replacing the yoshiko swift file with your latest commit. Still didn't work for me. Am I missing something?

**Comment by raulriera** [comment]
I don't know, if I don't see any code I can't help out much. But if its working in the sample project and not on yours, then something is definitely missing

**Comment by Karthikeyanbhc-33** [comment]
I'm working on Xcode 8.3 for building apps for IOS 11(It works by copying deployment target file of IOS 11 from Xcode 9 to Xcode 8.3). Your latest sample project is working fine with Xcode 9. But I want to use this textFieldEffects along with delegate features in Xcode 8.3 and swift 3.1. Is there any for me?

**Comment by raulriera** [comment]
1.4.0 is for xcode 9 only. You will need to use the previously released version for Xcode 8
