### ISSUE TITLE
Some effects are broken in iOS 11 due to changes in UITextField

### ISSUE THREAD

**Issue by mickychen0524** [raulriera/TextFieldEffects#134]
when focus on textfield, placeholder moves to bottom first and then animate to top on iOS 11

**Comment by raulriera** [comment]
Yeah, iOS 11 has changed quite a few things how layers and drawRect works... I have filled  radar with Apple...

**Comment by mickychen0524** [comment]
@raulriera thanks, please update this thread

**Comment by raulriera** [comment]
Apple confirmed that UITextField now fire drawRect when becoming first responders. So most effects are broken on iOS 11. I will need to think about a different approach to some of them, but no ETA at the moment

**Comment by raulriera** [comment]
Fixed in https://github.com/raulriera/TextFieldEffects/releases/tag/1.4.0
