### ISSUE TITLE
Swift 4

### ISSUE THREAD

**Issue by zoufishanmehdi** [raulriera/TextFieldEffects#135]
Hi, are they any plans to migrate to Swift 4 in the near future? Thank you.

**Comment by raulriera** [comment]
Hi, the code in master is in swift 4... at the moment there are some problems with how iOS 11 changed this so some textfields are broken https://github.com/raulriera/TextFieldEffects/issues/134 if you are not using any of those `master` should be a good starting point. But until all of them are fixed, there wouldn't be a new release :/

**Comment by raulriera** [comment]
Fixed in https://github.com/raulriera/TextFieldEffects/releases/tag/1.4.0
