### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by PedroAlcaide** [raulriera/TextFieldEffects#142]
I have this problem, and i can't use this CocoaPods. I use Xcode 9.1, Swift 3.2. 
Do you have any ideia whats my problem?

![captura de tela 2017-11-17 as 16 38 08](https://user-images.githubusercontent.com/11637665/32963027-bfaf7326-cbb5-11e7-8c27-100b7ec6cb33.png)

**Comment by raulriera** [comment]
If you are using master, you need to use Swift 4

**Comment by karaMartian** [comment]
Hi, I am having this problem too but I am using XCode 9.1, Swift 4 and these are the errors I get when I build 
<img width="273" alt="screen shot 2017-12-06 at 2 07 04 pm" src="https://user-images.githubusercontent.com/8404300/33661024-c6086a4c-da8e-11e7-9d75-b46d90e39f96.png">

**Comment by raulriera** [comment]
Which version of the library are you using?

**Comment by raulriera** [comment]
Strange, the code has the annotations https://github.com/raulriera/TextFieldEffects/blob/master/TextFieldEffects/TextFieldEffects/TextFieldEffects.swift#L118 but they are removed when used in Cocoapods? could this be a Cocoapods issues instead?

**Comment by karaMartian** [comment]
Yeah, the one I have doesnt have @objc on the func, it just says open func....

**Comment by karaMartian** [comment]
<img width="340" alt="screen shot 2017-12-06 at 7 45 27 pm" src="https://user-images.githubusercontent.com/8404300/33676289-10696b02-dabe-11e7-92fb-1ed1439d7689.png">

**Comment by raulriera** [comment]
You can just install it manually I guess, I don't understand why Cocoapods will strip that. But i haven't used cocoapods in years either 😔

**Comment by karaMartian** [comment]
That's weird, thank you
