### ISSUE TITLE
Problem with HoshiTextField

### ISSUE THREAD

**Issue by rami965** [raulriera/TextFieldEffects#144]
I am trying to use HoshiTextField and set the Inactive border color to white in storyboard
![screen shot 2017-11-29 at 10 29 13 am](https://user-images.githubusercontent.com/20938033/33365231-2c3bce48-d4f0-11e7-9cfd-bc685accff50.png)

![screen shot 2017-11-29 at 10 27 18 am](https://user-images.githubusercontent.com/20938033/33365193-03c8cbbe-d4f0-11e7-82c9-b40cab707722.png)
, but I see clear color although the active border color is working just fine

**Comment by raulriera** [comment]
Hi,

Is this a simulator? is it zoomed to 100%?

**Comment by rami965** [comment]
No, its my iPad

**Comment by raulriera** [comment]
Does this problem happens in the demo project?

**Comment by rami965** [comment]
Yes,
![screen shot 2017-11-29 at 5 09 59 pm](https://user-images.githubusercontent.com/20938033/33381988-36b54a1a-d528-11e7-9dfb-60bccf90bcf3.png)

**Comment by raulriera** [comment]
I can't reproduce this issue, can you provide more info than screenshots? iOS version, library version, actual code, etc. The example code works fine, as I mentioned before.. make sure the zoom is set to 100%

## iPad
![simulator screen shot - ipad air 2 - 2017-11-29 at 10 57 12](https://user-images.githubusercontent.com/24159/33384494-326eecd8-d4f4-11e7-963d-2f8747bca116.png)

## iPhone
![simulator screen shot - iphone se - 2017-11-29 at 10 57 29](https://user-images.githubusercontent.com/24159/33384511-38a27854-d4f4-11e7-88ba-ed21f6fe6932.png)
