### ISSUE TITLE
Text Effects not animating

### ISSUE THREAD

**Issue by daviddelmonte** [raulriera/TextFieldEffects#146]
I love this control, I am trying to use it in a UITableView, inside a UIViewController. Further, I'm using custom cells.

I can see the Placeholders in their correct positions, but there is no animation. Your demo project works fine.

I don't use:

` @IBOutlet private var textFields: [TextFieldEffects]!`

instead, in my custom cell class, I have this:

`@IBOutlet weak var detailTextField: TextFieldEffects!`

I'm setting the placeholder text in the `cellForRowAt`: method.

Can you tell me how many things I've messed up?

Thanks

David

**Comment by raulriera** [comment]
Hey. Have you tried using the actúa type instead of just TextFieldEffects? Use the full name of the effect you are trying to use and let me know how it goes. Also make sure you are not reloading the table when they are getting selected

**Comment by daviddelmonte** [comment]
Hi again. I realized that the cells were already populated, (Duh). When I created a new -- unpopulated record -- the control works as advertised. Apologies for the interruption..

**Comment by raulriera** [comment]
Glad you figured it out 🙂
