### ISSUE TITLE
HoshiTextField not getting padding.

### ISSUE THREAD

**Issue by neeraj92144** [raulriera/TextFieldEffects#150]
I want to give my textfield some padding from left but my code not applying to
 HoshiTextField but that code working in normal state please help me out code
 that is I am using right now as follows if you want to check out you can : ->       

        let rect = CGRect(x: 0, y: 0, width: 100, height: self.normalotxt.frame.height)        
        let paddingView = UIView(frame: rect)
        normalotxt.leftView = paddingView
        normalotxt.leftViewMode = UITextFieldViewMode.always

**Comment by raulriera** [comment]
Hi, 

The effects don’t take into consideration the left and right views. Sadly they are meant to use as is, or will require subclassing to accommodate for what you are trying to do

**Comment by neeraj92144** [comment]
My use here is to put some space before text and I want to put image on that place. Left side image that look as if it is on left side and text is on right side. It will look pretty as well. But in here I haven't found any same thing so I decided to put some space earlier and put image on that place. But still, if you have any assistance in this regard that will be most welcome from my side.

**Comment by konop** [comment]
Also had this issue @keshu1024 had a great solution but be aware to clean and rebuild.
