### ISSUE TITLE
half the effects don't work, better documentation

### ISSUE THREAD

**Issue by Nathan187** [raulriera/TextFieldEffects#151]
half of the effects don't work and there needs to be better documentation.  for example, if you are aware of the problem of using frameworks...then don't provide them.  just the source files.

**Comment by raulriera** [comment]
You should check the example project where you can see all the fields being used without any issues 😉

**Comment by Nathan187** [comment]
I have checked the example project.  I appreciate your efforts and responding.  Yet, still...the example project doesn't help much

**Comment by raulriera** [comment]
Any specific problem you are having? Most of the effects will need you to have a height constraint because they move around a lot in their space (labels flying into position, etc) which is how every one of them in the example were created.

**Comment by Nathan187** [comment]
let me mess around with it some more ...thanks for the quick responses (no sarcasm)
