### ISSUE TITLE
placeholderColor does not work

### ISSUE THREAD

**Issue by jameel-et** [raulriera/TextFieldEffects#154]
The placeholderColor does not work, it shows the active border Color only , if my active border color is yellow it will be yellow if i clear my active border color , the place holder will be invisible as well
<img width="596" alt="screen shot 2018-04-20 at 6 21 10 pm" src="https://user-images.githubusercontent.com/37223787/39076154-a877646c-44c7-11e8-9365-cb6ebf4de8cf.png">

See in the image the place holder color is white but showing yellow. Fix it please

**Comment by raulriera** [comment]
Does it show yellow when you actually compile the app? 

Pull requests are also welcome
