### ISSUE TITLE
its showing error when assigning a class to text field...

### ISSUE THREAD

**Issue by aniketborade5533** [raulriera/TextFieldEffects#157]
file:///Users/aniketborade/Desktop/Smart/Smart%20Girl%20+/View/Base.lproj/Main.storyboard: error: IB Designables: Failed to render and update auto layout status for LoginViewController (8HL-13-cZV): dlopen(TextFieldEffects.framework, 1): no suitable image found.  Did find:
	TextFieldEffects.framework: required code signature missing for 'TextFieldEffects.framework'

**Comment by raulriera** [comment]
> TextFieldEffects.framework: required code signature missing for 'TextFieldEffects.framework'

Looks like your framework is not signed

**Comment by analoguedarkness** [comment]
I ran into this using Xcode 10 Beta 2 and installing via CocoaPods, this is how I resolved the issue:

- Add the following to your Podfile:
`  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings.delete('CODE_SIGNING_ALLOWED')
      config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
  end`

- Then clean and rebuild your project. Bye Bye error!

**Comment by furkankadioglu** [comment]
Same problem here.
