### ISSUE TITLE
Hoshi TextField iOS 12 doesn't work perfectly

### ISSUE THREAD

**Issue by AlbertWu0212** [raulriera/TextFieldEffects#159]
![img_0186](https://user-images.githubusercontent.com/7083917/43053180-e022e762-8e5d-11e8-82b9-e5eb300cd8c2.png)
iOS 12 we can get a code from message app, after the field becoming first-responder, clicking the code will cause the field resignfirstresponder
![img_0185](https://user-images.githubusercontent.com/7083917/43053188-e6e6df86-8e5d-11e8-94db-23309c38ec6f.png)

**Comment by CoderFenchHU** [comment]
The same problem as me.  There is any solution for this?
