### ISSUE TITLE
Placeholder does not appear when programmatically setting text value

### ISSUE THREAD

**Issue by trinhngocthuyen** [raulriera/TextFieldEffects#16]
It turns out the placeholder does not appear when we programmatically set text for the text field. Please see the attached image for more information.

![textfieldeffects](https://cloud.githubusercontent.com/assets/8844044/8271406/216b7d16-1840-11e5-943c-190ade4b603c.png)

**Comment by trinhngocthuyen** [comment]
In the body of the func _*layoutPlaceholderInTextRect()*_ in HoshiTextField, there is a condition:
```
private func layoutPlaceholderInTextRect() {
   if !text.isEmpty {
      return
   }
}
```
This condition prevent the text field from layouting the placeholder label if the text is already set.
If we remove this condition, everything works perfectly

**Comment by raulriera** [comment]
Hi, which version are you using? I tested this with #13

**Comment by imfeemily** [comment]
Hi raulriera, latest version still found the same problem as trinhngocthuyen's issue.So when I remove this condition:

private func layoutPlaceholderInTextRect() {
  if !text.isEmpty {
      return
   }
}

It's work fine.

**Comment by raulriera** [comment]
This appears to affect only the `Hoshi` one. I will look into it

**Comment by raulriera** [comment]
Thanks guys, updated
