### ISSUE TITLE
Not working in xCode10 

### ISSUE THREAD

**Issue by Smiller193** [raulriera/TextFieldEffects#162]
I targeted the master branch and is still giving me errors

**Comment by raulriera** [comment]
Hi,

I will need way more information than that. Can you please verify that its working in the sample project in this repo? And then provide actual error information and steps that you are doing in order to use the library?

**Comment by Smiller193** [comment]
these are the errors that I am getting 

<img width="366" alt="screen shot 2018-09-20 at 4 32 17 pm" src="https://user-images.githubusercontent.com/16108750/45845320-d0716500-bcf2-11e8-98dd-c37ec5808258.png">

**Comment by Smiller193** [comment]
just using cocoapods to install/import

**Comment by raulriera** [comment]
I haven't used cocoa pods in years, I can't help you there sorry.

**Comment by Smiller193** [comment]
wait so i just can't use this library?

**Comment by raulriera** [comment]
That is what I meant by checking that it works in the sample project, if the problem is something with Cocoapods, then I can't be of any help there

**Comment by Smiller193** [comment]
i just want it to work for swift 4.2 and xcode 10

**Comment by Smiller193** [comment]
the demo seems to be working

**Comment by raulriera** [comment]
You are not paying attention to what I am saying. 🙁 `master` does compile with Xcode 10 and Swift 4.2. Which is why I'm suggesting to make sure it works for you in Xcode 10, I can't help you debug a Cocoapod issue, because I haven't used it in years (literally years)

**Comment by raulriera** [comment]
I have seen several issues about Cocoapods, the way it creates the framework is totally different apparently. Sadly that is also what people use the most :/ but I haven't seen any "Xcode 10" related so far... the previous ones where normally solved b the `.swift-version` file in the repo, but that one is set to 4.2

**Comment by Smiller193** [comment]
because I use this throughout my app so it not working is a little bad

**Comment by Smiller193** [comment]
the .swift-version file what solution is that

**Comment by Smiller193** [comment]
this is depressing it was working before

**Comment by katerynasytnykiOS** [comment]
@raulriera @Smiller193 I wonder if there's a problem with the new release - the version doesn't get bumped when installing with cocoapods.
 
When pointing to the default version like below it still installs 1.4.0 version, not 1.5.0 - I think that's the source of the problem:
pod 'TextFieldEffects'  

Pointing to the Swift 4.2 branch works and compiles fine:
pod 'TextFieldEffects', :git => 'https://github.com/raulriera/TextFieldEffects.git', :branch => 'swift-4.2'

**Comment by raulriera** [comment]
Hi Kateryna! thanks for the help, am I missing something in the pod spec? 🤔 https://github.com/raulriera/TextFieldEffects/blob/master/TextFieldEffects.podspec

**Comment by katerynasytnykiOS** [comment]
@raulriera actually, this is not an issue with your library. Usually it doesn't really matter but seems like this time it made a difference - cocoapods version itself installed locally on Mac was messing things up. Running "pod repo update" in terminal before running "pod install" fixed it (as well as other pods installation). Thanks for your patience!

@Smiller193 if you are still having this issue I'd suggest you run that and make sure that the version installed is 1.5.0. Also, if something is still stuck - another trick is to completely wipe out the installation of the pod by commenting out the pod line from the podfile, running "pod install" (that will remove the pod), and then uncommenting it out and running "pod install" again.

**Comment by Smiller193** [comment]
yeah pointing to the 4.2 branch still left me with errors

**Comment by Smiller193** [comment]
also tried uninstalling and installing many times, it didn't work

**Comment by Smiller193** [comment]
ehh maybe im just not meant to use this library because none of that worked

**Comment by katerynasytnykiOS** [comment]
@Smiller193 weird, sounds like something is cached on your machine.. I'd really play with Derived Data / closing Xcode / rebooting computer / cleaning cached data on your machine (e.g. sometimes running DrCleaner app does wonders). The code itself should compile fine though.

**Comment by Smiller193** [comment]
i mean i just added it manually for the time being

**Comment by ashishsj0** [comment]
@Smiller193  did you find any solution?

**Comment by ZacharyKhan** [comment]
Hmm, I'm running into the same issue. I've used this library for a while now with Cocoapods, I doubt it's related. If I find a fix, I will submit a PR.

**Comment by ashishsj0** [comment]
@All, this issue started with new Xcode update. Found the same issue in many other libs. While some of them are still working fine.

**Comment by elio-developer** [comment]
I have the same problem when importing through Cocopods and also when importing the classes directly. The demo project builds and run OK, but when adding the swift classes in my project, I'm getting the same errors as @Smiller193 Any thoughts?

**Comment by Smiller193** [comment]
@elio-developer i solved this problem by downloading the master branch taking the textFieldEffects that I needed. For example HoshiTextField and just dragging and dropping it into my project.  View Picture

<img width="213" alt="screen shot 2018-09-26 at 9 38 42 pm" src="https://user-images.githubusercontent.com/16108750/46118453-9281ae80-c1d4-11e8-8e2a-d5f3e6a0b2c9.png">

**Comment by ZacharyKhan** [comment]
@Smiller193 I did this too, but still get the same error as the OP.

**Comment by Smiller193** [comment]
@ZacharyKhan remove madokatextfield

**Comment by ZacharyKhan** [comment]
> @ZacharyKhan remove madokatextfield

@Smiller193 Should I keep everything else in the folder and _only_ remove `ModakaTextField`?

**Comment by Smiller193** [comment]
@ZacharyKhan yup that specific textfield gave me the error and I wasn't using it anyway so i took it out,

**Comment by ANSCoder** [comment]
@Smiller193 I have tested master branch demo code its working fine and also tested pod version 1.5.0 unable to see the problem like you in **Xcode 10.** 

<img width="335" alt="screenshot 2018-10-04 at 7 55 49 pm" src="https://user-images.githubusercontent.com/19596311/46480787-8ff40a00-c80f-11e8-87c0-532596900b1a.png">

**Comment by cherenkor** [comment]
Have same issue(

**Comment by ashishsj0** [comment]
Try to use the last stable pod version of text field effects and in build settings make sure the swift version in 3 or 4, not 4.2.

**Comment by raulriera** [comment]
Can you try pointing to this commit to see if that solves it for cocoa pods? 
https://github.com/raulriera/TextFieldEffects/commit/fa6207cc875564d41b931f278145e508d700fc9f

**Comment by yogeshmanghnani** [comment]
This works with the latest commit if I clone it from GitHub. But if I use it using CocoaPods it doesn't work. Seems like the CocoaPods is not pointing to the latest commit

**Comment by raulriera** [comment]
Are you sure you are updated? Cocoapods was also bumped here https://github.com/raulriera/TextFieldEffects/commit/97106a274acc611cca86d0c5de9df181bbb014eb and as seen in https://cocoapods.org/pods/TextFieldEffects

**Comment by miguel-adrecsa** [comment]
I solved this commenting the second line from:
platform :ios, "9.0"
to:
#platform :ios, "9.0

Not sure if that helps to anybody else :3

**Comment by yogeshmanghnani** [comment]
Seems to work perfectly now

**Comment by BrandtARMLS** [comment]
I dragged the folder in to my project. I set the class type to HoshiTextField. I see the new settings in Interface Builder. But when I run the app, I get the following errors logged:

2018-10-23 12:16:26.625348-0700 SweetTextFields[59380:6505762] libMobileGestalt MobileGestalt.c:890: MGIsDeviceOneOfType is not supported on this platform.
2018-10-23 12:16:26.688531-0700 SweetTextFields[59380:6505762] Unknown class HoshiTextField in Interface Builder file.
2018-10-23 12:16:26.691038-0700 SweetTextFields[59380:6505762] Unknown class HoshiTextField in Interface Builder file.
2018-10-23 12:16:26.714282-0700 SweetTextFields[59380:6505762] Failed to set (placeholderFontScale) user defined inspected property on (UITextField): [<UITextField 0x7f9eed84ae00> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key placeholderFontScale.
2018-10-23 12:16:26.714458-0700 SweetTextFields[59380:6505762] Failed to set (borderInactiveColor) user defined inspected property on (UITextField): [<UITextField 0x7f9eed84ae00> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key borderInactiveColor.
2018-10-23 12:16:26.714622-0700 SweetTextFields[59380:6505762] Failed to set (borderActiveColor) user defined inspected property on (UITextField): [<UITextField 0x7f9eed84ae00> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key borderActiveColor.
2018-10-23 12:16:26.714786-0700 SweetTextFields[59380:6505762] Failed to set (placeholderColor) user defined inspected property on (UITextField): [<UITextField 0x7f9eed84ae00> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key placeholderColor.
![screen shot 2018-10-23 at 12 13 37 pm](https://user-images.githubusercontent.com/26446141/47384945-8a2a6f80-d6bd-11e8-8001-a371f231c738.png)

**Comment by purevdorjsodnomdorj** [comment]
[_txtUsername setValue:[MyConfig getMyConfig].myColor forKey:@"borderActiveColor"]; 

Failed to set (borderInactiveColor) user defined inspected property on (UITextField): [<UITextField 0x7fc1a602ea00> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key borderActiveColor.

**Comment by drewbrns** [comment]
I was facing the same issue, to fix it, I included post install script to set the swift version to 4.2
`  post_install do |installer|
    installer.pods_project.targets.each do |target|
        if ['TextFieldEffects'].include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.2'
            end
        end
    end
  end`
