### ISSUE TITLE
Getting error in swift 4.2

### ISSUE THREAD

**Issue by NStreet8579** [raulriera/TextFieldEffects#171]
1. Type 'UITextField' has no member 'textDidEndEditingNotification'
2. Type 'String' has no member 'square'

Please help!

**Comment by raulriera** [comment]
Hi, please check the closed issues as they are several mentions of swift 4.2, the demo project is in swift 4.2 as well. Are you able to compile that one?

**Comment by raulriera** [comment]
You are not able to compile the demo project?

**Comment by NasirMalik** [comment]
+1 Facing same issue

**Comment by raulriera** [comment]
Guys, if you don't provide: information, a sample project, code, anything. These are not very helpful

**Comment by frednovack** [comment]
Was having the same issue... just changed the swift version from the framework target at the pods project and it worked 
![screen shot 2018-12-20 at 20 06 27](https://user-images.githubusercontent.com/15111867/50313557-e4179d80-0492-11e9-84b9-6dc82de1aad2.png)
