### ISSUE TITLE
The Kaede sliding text over shoots the constraints on the first tap then after that it returns to bounds.

### ISSUE THREAD

**Issue by johnlietzke** [raulriera/TextFieldEffects#175]
Thanks for the great pod.  It is so easy to use and works without any installation hassle.  The best part is the way in which you payed out the custom class so that all the features are straight forward.

My only issue is the Kaede sliding text over shoots the constraints on the first tap then after that it returns to bounds.

Thanks again,

John

**Comment by raulriera** [comment]
Hey John,

Thanks for the kind words, can you provide some code and a gif or what you are referring? Is it happening in the demo project as well?

**Comment by johnlietzke** [comment]
A well deserved compliment.

It is not happening in the demo project.  What I believe is happening is that I am using a picker triggered by Editing Did Begin and it is calling editing did begin multiple times once on the initial launch of the picker and again when it populates the textfield.  

Any ideas on how to resolve this.  It may be approach.

It only happens under certain circumstances in the upper textfield and works perfectly when the textfield is populated from the keyboard in the lower textfield.

**Comment by johnlietzke** [comment]
I also happens when I remove the Editing Did Begin and populate the upper textfield from the lower textfield.  There seems to be something that is triggering the textfield more than once.  I also tried using endEditing(true) to no avail.

**Comment by raulriera** [comment]
Can you make it reproduce in a piece of code I can’t check?

**Comment by johnlietzke** [comment]
I think the picker pod I am ushering is the issue.  I can not reproduce the results from a straight code standpoint.  Sorry for wasting your time.  I am going to find another popup picker that does not use a sender call back.

Your responsiveness is really great.  I know also as a developer that finding the time and energy to support a free product is challenging.  Your interest in resolving my problem is greatly appreciated.


John

**Comment by raulriera** [comment]
Thanks John 😍, let me ‘now if that fixes it

**Comment by otymartin** [comment]
@johnlietzke @raulriera 
I wonder if this is the issue he's describing. I made a youtube video. I never had this problem until now.
https://youtu.be/eUm-SwlR750

**Comment by johnlietzke** [comment]
I was able to resolve the issue.  It had to do with constrains.  Lots of trial and error.  I was populating the textfield from a dialog and that was where the problem occurred.

Thanks for checking in.

**Comment by otymartin** [comment]
@johnlietzke 
What do you mean by this `I was populating the textfield from a dialog and that was where the problem occurred.`

**Comment by johnlietzke** [comment]
I was using editing did begin improperly and it was never clearing the text.  It had nothing to do with Keade.

**Comment by otymartin** [comment]
@johnlietzke So is the issue I documented in my youtube video separate or the same as what you were experience - Just so I'm on the same page 👍

**Comment by johnlietzke** [comment]
Separate.  The way I was calling it caused the action editing did end and editing did change to both occur.

**Comment by otymartin** [comment]
Oh I see. I don't think you solution solves my problem. I removed UITextFieldDelegate and still see the problem so I need to dig further.

Thanks for documenting your issue and responding in near realtime 🥇

**Comment by johnlietzke** [comment]
The constraints may play a part in in especially the trailing.
