### ISSUE TITLE
HoshiTextField palce holder can't change padding and it not in right place 

### ISSUE THREAD

**Issue by mohamadhero15** [raulriera/TextFieldEffects#182]
hi
there is a little problem i tried to fix it with `    private let textFieldInsets = CGPoint(x: -6, y: 16)
` but it didn't change anything 
as you can see the placeholder text is on the bottom border and I tried to change alignment as you can see but nothing changed

![Screen Shot 2019-07-29 at 4 45 30 PM](https://user-images.githubusercontent.com/23268986/62047688-58cc6a80-b220-11e9-9500-eeae151e19b0.png)

**Comment by raulriera** [comment]
Hi,

Yeah, changing the position of things is not supported by the library, only how things look (Color, sizes, etc)
