### ISSUE TITLE
Can I customize it somehow to give the Akira a corner radius?

### ISSUE THREAD

**Issue by lehoangthai** [raulriera/TextFieldEffects#188]

**Comment by raulriera** [comment]
You can always apply corner radius to views in iOS, but if you want to tweak it directly you can also drop the files into your project and modify it

**Comment by lehoangthai** [comment]
private func updateBorder() {
        borderLayer.cornerRadius = 5
        borderLayer.frame = rectForBounds(bounds)
        borderLayer.borderWidth = (isFirstResponder || text!.isNotEmpty) ? borderSize.active : borderSize.inactive
        borderLayer.borderColor = borderColor?.cgColor
    }

It works in the storyboard but doesn't work when running a virtual machine

> You can always apply corner radius to views in iOS, but if you want to tweak it directly you can also drop the files into your project and modify it

**Comment by lehoangthai** [comment]
I did it, thank you
