### ISSUE TITLE
iOS 13 placeholder font for HoshiTextField

### ISSUE THREAD

**Issue by StarWars** [raulriera/TextFieldEffects#189]
Hi,
it's no longer reliable in iOS 13 to access fonts the way it's done in the library. i.e:
`private func placeholderFontFromFont(_ font: UIFont) -> UIFont! {
        let smallerFont = UIFont(name: font.fontName, size: font.pointSize * placeholderFontScale)
        return smallerFont
    }`

![image](https://user-images.githubusercontent.com/803292/65772143-f4ebf280-e139-11e9-91b3-7949ee949088.png)
https://developer.apple.com/videos/play/wwdc2019/227/

That seems to be the reason for the placeholder label, to use a default font instead of the expected one, on iOS 13.

![image](https://user-images.githubusercontent.com/803292/65772321-48f6d700-e13a-11e9-91d5-49cecf3d1fc0.png)

Please note, that the problem is valid only when working with system fonts.

**Comment by f0r3s1** [comment]
THE SAME!!!
Is anyone has a solution to solve?

**Comment by raulriera** [comment]
Does the pull request solve your issue?

**Comment by tadeha** [comment]
I have the same problem.

**Comment by raulriera** [comment]
Fix target master, a fix has been merged by @erenozkul
