### ISSUE TITLE
Unknown class _TtC16TextFieldEffects14HoshiTextField in Interface Builder file.

### ISSUE THREAD

**Issue by tonychan818** [raulriera/TextFieldEffects#19]
Hi, I got this error at run time. 
I just drag the TextFieldEffects folder to my project:
![screen shot 2015-07-13 at 5 55 13 pm](https://cloud.githubusercontent.com/assets/5890291/8647191/58007102-2988-11e5-97a8-69c701846c7f.png)

and use it in my XIB:

![screen shot 2015-07-13 at 5 54 05 pm](https://cloud.githubusercontent.com/assets/5890291/8647192/5fdd74e2-2988-11e5-9f30-9150eadc3eb3.png)

and I got this warning:

![screen shot 2015-07-13 at 5 54 09 pm](https://cloud.githubusercontent.com/assets/5890291/8647195/6532b1e6-2988-11e5-87ee-7f12f26c0b19.png)

at run time i got this error

Unknown class _TtC16TextFieldEffects14HoshiTextField in Interface Builder file.

Failed to set (borderInactiveColor) user defined inspected property on (UITextField): [<UITextField 0x12dd96030> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key borderInactiveColor.

any idea :( ?

**Comment by raulriera** [comment]
is this an standalone Xib file? I haven't tried it wit those... do you have the same problems in an storyboard?

Do you still get this error when running the sample project?

**Comment by tonychan818** [comment]
yes, it is a standalone Xib file, and I dont get this error when running the sample project. Thanks

**Comment by raulriera** [comment]
Have you tried deleting the module part? Since you are not using it as a framework, you don't really need the module

**Comment by tonychan818** [comment]
it works now!! many thanks

**Comment by raulriera** [comment]
Sweet
