### ISSUE TITLE
Placeholder text is extending outside the Text field Area

### ISSUE THREAD

**Issue by vineethvijayan** [raulriera/TextFieldEffects#192]
![Screenshot 2019-10-17 at 7 27 32 PM](https://user-images.githubusercontent.com/6049347/67015457-3148b800-f114-11e9-8cdb-9ef1a15931f4.png)

I am using Hoshi Text field.

**Comment by raulriera** [comment]
Hi, none of the effect support left or right views. If you would like that feature you need to change the calculation of `rect` in the files and include the rect of those views as well
