### ISSUE TITLE
Place holder font is different than the standard font

### ISSUE THREAD

**Issue by MrPereir4** [raulriera/TextFieldEffects#194]
When I try to use any of the text fields, the placeholder font is not equal to the app standard one, but when I run the app on iOS 12, works fine, the problem is on iOS 13.

**Comment by raulriera** [comment]
Hi,

Can you please try the `master` version (either by downloading the code or using Swift Package Manager) and let me know if the problem persists?

**Comment by iOSDevFin** [comment]
I have the same issue. I updated my Podfile to

pod 'TextFieldEffects', :git => 'https://github.com/raulriera/TextFieldEffects.git', :branch => 'master'

But it's ignoring any font settings on the textfield. Can you please fix that?

**Comment by raulriera** [comment]
If the code in master is not fixing it, a PR is very welcome. I can't seem to reproduce that problem

**Comment by MrPereir4** [comment]
What is PR???

**Comment by raulriera** [comment]
PR = Pull Request, when you contribute code using this website Github

**Comment by mprey** [comment]
Having the same issue even on latest master branch

**Comment by Majituteniyazov** [comment]
@raulriera please help to solve this problem. I'm on latest master branch. I'm using HoshiTextField and system font is not standard font

**Comment by raulriera** [comment]
Could someone elaborate more on the problem? I can't do anything if I don't see what is wrong, what you are doing, which branch, swift, Xcode, etc. And most importantly, make sure the demo project doesn't reflect the problem you are describing

<img width="487" alt="Screen Shot 2019-11-15 at 9 46 47 AM" src="https://user-images.githubusercontent.com/24159/68951844-d941b780-078c-11ea-84e3-0f1a3d8c1e42.png">

**Comment by dterekhov** [comment]
Hello guys!
I use `AkiraTextField` type only so I will show an example on it.

`AkiraTextField .swift`
This function get in parameter for example native ".SFUI-Regular" but returns "Times New Roman" that looks not so nice in my opinion.
```private func placeholderFontFromFont(_ font: UIFont) -> UIFont! {
        let smallerFont = UIFont(name: font.fontName, size: font.pointSize * placeholderFontScale)
        return smallerFont
    }```
I use Storyboard with added `AkiraTextField` on it.

User Defined Runtime Attributes setup like that:
borderColor = UIColor.clear
placeholderColor = UIColor.white
placeholderFontScale = 0.85

Maybe it can be helpful to debug this edge case.

**Comment by edwardkunz** [comment]
@raulriera Having the same font issue and I think it has something to do with iOS 13 or XCode 11.2.
Maybe it is related to this: https://stackoverflow.com/questions/58706570/how-can-i-find-the-source-of-this-font-related-coretext-warning-in-ios13

Error in the log:

> CoreText note: Client requested name ".SFUI-Regular", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[UIFont systemFontOfSize:].

**Comment by raulriera** [comment]
No one has confirmed that this happens in the demo project, can you please verify it there before commenting here? I can't reproduce the issues you are commenting

<img width="487" alt="Screen Shot 2019-12-07 at 12 09 52 PM" src="https://user-images.githubusercontent.com/24159/70378085-7d310580-18ea-11ea-8603-cede206f625f.png">
