### ISSUE TITLE
Hoshi Placeholder wrongly placed when Textfield is firstResponder

### ISSUE THREAD

**Issue by DieGlueckswurst** [raulriera/TextFieldEffects#198]
When setting `textField.becomeFirstResponder()` inside `viewDidLoad`  the placeholder is placed slightly to the left. Why does this happen and how can I fix it?

Here is a screenshot for a better understanding: 

[https://imgur.com/a/AsxMgtB](url)

**Comment by raulriera** [comment]
`viewDidLoad` hasn't finished calculating the sizes of your view controller, have you tried using `viewWillAppear`? Technically this is the event you want if you want to display the keyboard

**Comment by DieGlueckswurst** [comment]
Tried this: `override func viewWillAppear(_ animated: Bool) {
//        self.emailTextField.becomeFirstResponder()
    }`  but that doesn't change anything

**Comment by raulriera** [comment]
You need to call `super.viewWillAppear(animated: animated)` before your first responder

**Comment by DieGlueckswurst** [comment]
Didn't work either :(  Pretty sure the constraints are correct. You can just look at my git: 

[https://github.com/DieGlueckswurst/Wishlist](url)

Just run the project and click on "Mit Email fortfahren". 
The code is inside ViewControllers -> StartingVC -> EmailVC

**Comment by raulriera** [comment]
You seem to be overwriting the rect methods, try using the library directly to see if the problem persists https://github.com/DieGlueckswurst/Wishlist/blob/5d8a09ce9db4fe53f22c66f1684a158bb77a0e1f/Wishlist/Helpers/TextfieldExtensions/CustomTextField.swift

If not, please try to reproduce on the demo project

**Comment by DieGlueckswurst** [comment]
Ok I created a demo project and it is not the same error but now the Textfield doesn't get displayed at all if I call `becomeFirstResponder` 

Here is the demo project: [https://gofile.io/?c=j9qqLn](url)

**Comment by DieGlueckswurst** [comment]
any idea why that happens?

**Comment by raulriera** [comment]
Sorry, when I mentioned demo project I mean the one that comes with the library

**Comment by DieGlueckswurst** [comment]
sorry I am not quite following you there, don't know too much about git. Could you just use my demoproject? Or maybe try it out yourself in one of your projects? If it is working for you then I know that I messed up myself :)

**Comment by DieGlueckswurst** [comment]
any Updates on this?

**Comment by DieGlueckswurst** [comment]
any updates on this?

**Comment by raulriera** [comment]
Hey, no... you haven't done what I requested. https://github.com/raulriera/TextFieldEffects/issues/198#issuecomment-579879618 this library comes with a demo project, can you please reproduce the problem there?

**Comment by DieGlueckswurst** [comment]
alright, I reproduced the problem and uploaded it :)  You can also very easily try it yourself by just calling "becomeFirstResponder" inside "viewDidLoad". Like I said in the comments above, calling it inside `viewWillAppear` is not solving the problem :/

**Comment by DieGlueckswurst** [comment]
did you see what I uploaded ?
