### ISSUE TITLE
use programmatically

### ISSUE THREAD

**Issue by codeSupreme** [raulriera/TextFieldEffects#2]
How do you use this programmatically (without storyboard)? I am unable to instantiate the KaedeTextField as there are no constructors.

**Comment by raulriera** [comment]
Are you using the Carthage install? I am having problems with Carthage at the moment. If you use the manual way I am able to create `KaedeTextField()` with no problems, since it's a subclass of UITextField you still have that initialiser and the `KaedeTextField(frame:CGRect)` one

**Comment by codeSupreme** [comment]
I am doing manual. I tried the KaedeTextField() but am getting "no
accessible initializers". I will try again

**Comment by raulriera** [comment]
Check out this working example in your viewDidLoad (or any other place)

```swift
let anotherText = KaedeTextField(frame: CGRect(x: 20, y: 20, width: 200, height: 40))
anotherText.foregroundColor = UIColor.redColor()
view.addSubview(anotherText)
```

Hope that helps!

**Comment by jason7toxic** [comment]
Hi raulriera,

May I know what did I miss?
![screen shot 2015-05-25 at 2 39 20 pm](https://cloud.githubusercontent.com/assets/9715369/7792978/ee7d7058-02eb-11e5-9755-870ae580d346.png)

**Comment by raulriera** [comment]
Hi, you need to import the TextFieldEffects framework at the top

**Comment by jason7toxic** [comment]
Hi,

Thx bro
Thanks for your patient against my noobiie question =P
