### ISSUE TITLE
Placeholder label text not changing

### ISSUE THREAD

**Issue by tusharMistri** [raulriera/TextFieldEffects#200]
Hello,

**issue** : I want to change placeholder label text, As of now it's taking what i will set into the placeholder text in textfield, Label will displaying with same text with all capital text. I want to change first character is capital and other all are small. How i can change it.

Thank you.

**Comment by raulriera** [comment]
Hi,

The library is as is, there are no further customization options apart from the ones already implemented. If you would like to add new features, please fork the project and implement them locally

**Comment by ZacharyKhan** [comment]
@raulriera It seems there are merged PR's, such as #191, that are merged into `master` but the pod trunk had not been updated. If you have to intention of supporting this library further, would you be open to assigning contributors to continue supporting TextFieldEffects?

I would be happy to continue to maintain the library and manage code review if that is not of interest to you as I feel this is a great lightweight library for developers to use.

**Comment by raulriera** [comment]
Hey Zachary,

Thanks for the offer, but the library is intentionally not looking to expand it further. I would love some help doing code reviews and bug fixes, but I don't think we should add more effects or provide more features to them. Most importantly because the latter can be eternal

**Comment by ZacharyKhan** [comment]
I understand, I agree with the statement that new features should not be added. If you can update Cocoapods with the existing fixes merged into master that would be appreciated :) I currently have fixes manually implemented into the library

**Comment by raulriera** [comment]
How can I add you as a contributor to cocoa pods? Also, you can just point the Podfile to master, no need to update the trunk

**Comment by ZacharyKhan** [comment]
Yes, but pointing to master without releases makes it harder and harder over time to revert to a known working & stable release if the need to revert was ever required 😄I plan to use this library in a production application I am working on.

My suggestion is to continue pushing out releases on Github and updating the pod trunk alongside these releases, even if the updates only contain bug fixes and no new features. If you would like my help in doing so, I am happy to do so. If not, no worries! I can fork the master repo and maintain it locally for my needs 😃 

If you'd like me to help maintain and push releases with bug fixes, you can add me to the pod trunk by running 👇 
```bash
pod trunk register zachary.khan3@gmail.com 'Zachary Khan' --description='GitHub contributor'
```

I may also need authorization to create new releases (tags) on Github for Cocoapods to point at, unless you'd like to manage creating new releases every time.

**Comment by raulriera** [comment]
Thanks, sent.

**Comment by ZacharyKhan** [comment]
Got it, thanks Raul 👍

**Comment by raulriera** [comment]
New github release is up too

**Comment by ZacharyKhan** [comment]
`1.7.0` release should include the updated podspec to reflect the new version. Can you update the release and master branch to include this and I can then push to cocoapods trunk?
