### ISSUE TITLE
Module compiled with Swift 5.1.2 cannot be imported by the Swift 5.2 compiler

### ISSUE THREAD

**Issue by DieGlueckswurst** [raulriera/TextFieldEffects#202]
Updated XCode today and I am getting the above error message. 

Found this on Git: [https://stackoverflow.com/questions/58654714/module-compiled-with-swift-5-1-cannot-be-imported-by-the-swift-5-1-2-compiler](url)

Would be awesome if you could update it so it's running again :)

**Comment by raulriera** [comment]
Hey,

Have you tried generating the project again? I would recommend Swift Package Manager

**Comment by DieGlueckswurst** [comment]
How exactly  can I do that?

**Comment by DieGlueckswurst** [comment]
@raulriera I did some more research and and it seems that I could fix it by downgrading Xcode but that doesn't make too much sense. The best way to fix it is that you would bring out an updated version, build in the latest Swift-Version. I would really appreciate your help :)

**Comment by DieGlueckswurst** [comment]
@raulriera any updates? Sorry if I annoy you but its quite urgent :(

**Comment by raulriera** [comment]
Hey, sorry no... I recommend using the library directly (not as a cocoapods) via submodule, or Swift Package Manager will help you solve these issues.
