### ISSUE TITLE
HoshiTextField inactive state line does not appear

### ISSUE THREAD

**Issue by AnmolRattan007** [raulriera/TextFieldEffects#203]
<img width="260" alt="Screenshot 2020-04-04 at 2 16 09 PM" src="https://user-images.githubusercontent.com/56048201/78422719-fc5afe00-767e-11ea-8e34-bd0b86229613.png">

Response in Simulator:

<img width="203" alt="Screenshot 2020-04-04 at 2 16 28 PM" src="https://user-images.githubusercontent.com/56048201/78422722-0b41b080-767f-11ea-87c4-7c8c3b330b40.png">

**Comment by raulriera** [comment]
Hi, please try the demo project to see what you are missing in your installation. Sound like an issue with the text field size. The demo project should give you a head start

**Comment by AnmolRattan007** [comment]
I have unexpectedly set the border width of Fields which was causing the issue. By the way thanks for your time.

**Comment by raulriera** [comment]
Hmmm that makes sense, the textfields need to be unstyled in other for everything to work. Thanks!
