### ISSUE TITLE
Failed to set (placeholderColor) user defined inspected property on (UITextField)

### ISSUE THREAD

**Issue by wugensan** [raulriera/TextFieldEffects#21]
I got this error when the app is about to run.
![image](https://cloud.githubusercontent.com/assets/7478622/9149541/07c2de14-3de2-11e5-9baa-2c95cdc61e86.png)
I simply drag the files to my project:
![image](https://cloud.githubusercontent.com/assets/7478622/9149545/31bf4518-3de2-11e5-97da-54c8571f1520.png)
And the settings in my xib is:
![image](https://cloud.githubusercontent.com/assets/7478622/9149554/60a1dd64-3de2-11e5-8ff6-80cf9d19afc4.png)
The project can be compiled successfully. But when it's about to run, it stops and print the log:
![image](https://cloud.githubusercontent.com/assets/7478622/9149585/b0e35e46-3de3-11e5-9a19-14357716f6cf.png)
Any help?

**Comment by wugensan** [comment]
Ignore this issue, I made stupid mistake and have fixed it.

**Comment by raulriera** [comment]
Im glad you found the solution :)
