### ISSUE TITLE
drawViewsForRect method being call multiple times

### ISSUE THREAD

**Issue by zhouhao27** [raulriera/TextFieldEffects#22]
Since this method is called a few times, the foregroundView and placeholderLabel will be add multiple times. I think this is not very elegant, need to consider only add them only once. Am I right?

**Comment by raulriera** [comment]
Hello,

I thought the same, but I couldn't find any evidence of the views redrawing on top of each other. I am of course open to suggestions :)
![screen shot 2015-08-13 at 09 20 04](https://cloud.githubusercontent.com/assets/24159/9245486/5d8c8bde-419c-11e5-8d77-d7cf0e5ef7be.png)

Thanks for the report!

**Comment by iltercengiz** [comment]
I thought the same as @zhouhao27 
Although I haven't tested it, it would be good to check if placeholderLabel has a super view and if not, add it as a subview.

**Comment by raulriera** [comment]
Although the same instance of something can't be added several times to a view, the are not getting stacked on top of each other... but I do find it confusing that addSubview has no `guard`. I will update the code to reflect better what is going on
