### ISSUE TITLE
placeholder image

### ISSUE THREAD

**Issue by kiwo12345** [raulriera/TextFieldEffects#26]
Is there any way to add a image to the placeholder? Or at least pin a image beside it so that it follows it?

**Comment by raulriera** [comment]
Hi, no there isn't at the moment. :)

**Comment by kiwo12345** [comment]
Okey, I will try to work something out then :)
Thanks for sharing this btw!

**Comment by raulriera** [comment]
Cool, if you can please share it 😬 Thank you for stopping by :dancers:
