### ISSUE TITLE
UITextView

### ISSUE THREAD

**Issue by Urkman** [raulriera/TextFieldEffects#28]
Any chance to get this for a UITextView?

**Comment by raulriera** [comment]
Hi Stefan, I thought about it at one point... but not all of the effects will suit UITextViews as well as these.

**Comment by Urkman** [comment]
That's right... Not all will fit exactly... 
But with some of them i would work :)

**Comment by annehiro** [comment]
How about using a textfield as textView? Can we just increase the number of lines?

**Comment by annehiro** [comment]
I am using KaedeTextField and need a field for a description that will be multi line. Do you have any suggestions as to what I can do. Thanks!

**Comment by raulriera** [comment]
Hey @annehiro , I would suggest creating a KaedeTextView that will have the same effect as the TextField. But depending on the size of that view, it could look pretty weird a giant portion of the screen sliding to the right 😅

**Comment by annehiro** [comment]
Haha I will show you how it turns out.

**Comment by raulriera** [comment]
Closing this, maybe a new repo about TextViews should be created :)

**Comment by eikebartels** [comment]
Any news on this front? @annehiro did you find a nice solution?
