### ISSUE TITLE
Changing font size of placeholder

### ISSUE THREAD

**Issue by iagomr** [raulriera/TextFieldEffects#29]
Hi,

Would there be a way to change the font of the placeholder?

Thank you for the work on the framework!

**Comment by raulriera** [comment]
Hi,

At the moment it uses the same font as the textfield itself, do you mean to have on entirely different to the one of the textfield? I didn't plan for that yet

**Comment by iagomr** [comment]
Yes, that was it. Thanks anyway!

**Comment by raulriera** [comment]
Fixed in 141c2b0d69, will added to the rest of the effects later today :)
