### ISSUE TITLE
How do you call UITextField delegate methods from viewControllers?

### ISSUE THREAD

**Issue by pahnev** [raulriera/TextFieldEffects#3]
As I understand you are overriding `textFieldDidBeginEditing` and  `textFieldDidEndEditing`methods. This leads that we can't call those in viewController to do any additional work on textFields.

Could be also that I just don't know enough what's happening.

**Comment by raulriera** [comment]
You can override them in your viewController as well, just remember to call super

**Comment by pahnev** [comment]
So setting delegate in ViewController to self? Inside init method? If yes then I'm not getting it.

````
    required init(coder aDecoder: NSCoder) {
        super.init(coder:aDecoder)
        let text = HoshiTextField()
        textField = text
        text.delegate = self
    }
```

I've tried setting delegate in storyboard, in that init straight to the outlet and the way you said.

**Comment by raulriera** [comment]
No, if you are using the storyboard then you IBOutlet the textfields into the ViewController and set the delegates there

**Comment by pahnev** [comment]
Yup exactly what I think I'm doing. Check my fork.

**Comment by raulriera** [comment]
Hmmm you are right, I am doing something terrible wrong here... I will investigate of a better way to call those 2 animation methods :/

**Comment by raulriera** [comment]
There is a solution, to remove the delegate from the custom textfields and implement something like this https://gist.github.com/raulriera/13ab88f0040af793307b and then simply remove the `delegate = self` from the custom textfields.

But this feels so wrong!

**Comment by pahnev** [comment]
I think notifications is the way to go. Take a look at this library: https://github.com/lexrus/LTBouncyPlaceholder

**Comment by raulriera** [comment]
Pushed 0b3a0abb6 thanks for filing this! I will still keep an eye on the solution to see if there is a better way.

Thanks again

**Comment by hdoria** [comment]
I can't call textFieldDidBeginEditing on my viewcontroller. What am i doing wrong?

```swift
override func viewDidLoad() {
        super.viewDidLoad()
        self.txtEmailAddress.delegate = self

    }
```

**Comment by raulriera** [comment]
Hi @hdoria , are you using the latest version?
