### ISSUE TITLE
i get this error:"Main.storyboard: error: IB Designables..."

### ISSUE THREAD

**Issue by 85636682** [raulriera/TextFieldEffects#37]
file:///Users/stephen/iphone/Kitchen/Kitchen/Base.lproj/Main.storyboard: error: IB Designables: Failed to render instance of HoshiTextField: Rendering the view took longer than 200 ms. Your drawing code may suffer from slow performance.

**Comment by raulriera** [comment]
Do you get this error on the Example project?

**Comment by 85636682** [comment]
i don't try on the example project

**Comment by raulriera** [comment]
Is that the only thing you get? is the textfield working besides that?

**Comment by raulriera** [comment]
I will close this for now, if you have more info or can submit a project where the error occurs please comment and reopen it
