### ISSUE TITLE
Support for Right to Left languages

### ISSUE THREAD

**Issue by raulriera** [raulriera/TextFieldEffects#38]
🙌

**Comment by mohammad19991** [comment]
when is this problem gonna be solved? any updates! Thanks

**Comment by raulriera** [comment]
There is no work on this at the moment. Always open to pull requests

**Comment by raulriera** [comment]
Added support for RTL on Kaede https://github.com/raulriera/TextFieldEffects/commit/af3fee1103613e4ba4e10c9858b8a317f7cd4d9b

**Comment by abhijithExperion** [comment]
I still feel the problem on Hoshi Text field for Arabic(RTL). It is not getting changed

**Comment by raulriera** [comment]
It is, this ticket is still open. There is no RTL support at the moment, just for the default implementation of Kaede
