### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by skywinder** [raulriera/TextFieldEffects#4]
Please, provide Carthage support to make installation easier.

**Comment by raulriera** [comment]
I tried, but there seems to be something wrong that is also affecting "Spring" https://github.com/Carthage/Carthage/issues/335 

Do you have any ideas about a possible fix?

**Comment by skywinder** [comment]
Have no idea, I'm also new with carthage. Y
ou can also try to use cocoa pods, since last release support swift.

**Comment by raulriera** [comment]
Strangely packing up the framework Xcode is removing methods from the project, so I won't be supporting Carthage anytime soon apparently. You can still use the project by drag and dropping the file directly into your project

**Comment by skywinder** [comment]
Ok. Anyway tThanks for awesome TF's!

**Comment by raulriera** [comment]
I have pushed a fix that make Carthage work for creating textfield by code. But I am still unable for the IBDesignable items to appear on Storyboards. I think Xcode is just trolling me by now

**Comment by skywinder** [comment]
Ok, I will check it and let you know, if find something, that can help you.

**Comment by raulriera** [comment]
Solved. For Storyboard support make sure your project has a build setting of `EMBEDDED_CONTENT_CONTAINS_SWIFT` to true

**Comment by skywinder** [comment]
Awesome, thanks! :+1:

**Comment by skywinder** [comment]
BDW, now I switching back to CocoaPods for most of the projects (as for me - it's more convenient way to maintain dependencies).

**Comment by raulriera** [comment]
I believe this a limitation of .frameworks in general, as long as the .framework is created and imported externally, the IB Designables are gone...

Would gladly accept a pullrquest for cocoa pods support :dancers:
