### ISSUE TITLE
Any way to adjust the clear button location 

### ISSUE THREAD

**Issue by walsht** [raulriera/TextFieldEffects#40]
Any way to adjust the clear button location to center on field?

<img width="320" alt="screen shot 2015-11-09 at 5 51 47 am" src="https://cloud.githubusercontent.com/assets/1455799/11033073/0c5d727e-86a6-11e5-9b13-e2321c497e67.png">

**Comment by raulriera** [comment]
Hi Tim, they will need to include the rect in `clearButtonRectForBounds`.

**Comment by simonlinj** [comment]
Since TextFieldEffects is just an UITextField's subclass. You can override ```clearButtonRectForBounds``` and place it wherever you want.

```
override func clearButtonRectForBounds(bounds:CGRect) -> CGRect {
   //calculate and return the position for the clearButton
}
```


reference: https://developer.apple.com/library/ios/documentation/UIKit/Reference/UITextField_Class/#//apple_ref/occ/instm/UITextField/clearButtonRectForBounds:
