### ISSUE TITLE
README should state minimum iOS version

### ISSUE THREAD

**Issue by cauli** [raulriera/TextFieldEffects#47]
Lots of us still need to support iOS 7, is this possible with TextFieldEffects?

Thanks!

**Comment by raulriera** [comment]
Hi,

Sorry but I don't support iOS 7 of anything right now, have you tried changing the iOS version and compiling it?

**Comment by cauli** [comment]
It doesn't compile because dynamic libraries is used for CocoaPods.
Maybe it is possible without Cocoapods (manual insertion) and some little tweaking of code?

I have no experience with iOS plugins, but I might take a look into it. 
A co-worker used the plugin and it is really nice but we need to support iOS7 :)

Thanks for your time!

**Comment by raulriera** [comment]
Yeah, you can't use .frameworks files in iOS7... The thing is that Cocoapods forces you to use .frameworks when the code is in Swift. So the only solution would be to drag and drop the files into your project directly :(

**Comment by cauli** [comment]
Got it working! I added the files manually, and had to 
![downgrade](http://cau.li/things/textfield.png) TextFieldEffects deployment target to 7.0. 

Suggestion: Defaulting the deployment target of TextFieldEffects to 7.0 and declaring this info on README the help other noobies like me!

Thanks for your help!

**Comment by raulriera** [comment]
Excellent, glad it worked out :)
