### ISSUE TITLE
How do I change border color in MinoruTextField?

### ISSUE THREAD

**Issue by Jackson0111** [raulriera/TextFieldEffects#48]
This might be a stupid question, but I can't find a function to do it.

**Comment by raulriera** [comment]
Hi,

You can't, Minoru uses the text color as the border color.

**Comment by Jackson0111** [comment]
I see, another question tho. Can I change border thickness?

**Comment by raulriera** [comment]
No :( but since they are subclass able, you can override this

```
override public func animateViewsForTextEntry() {
        borderLayer.borderColor = textColor?.CGColor
        borderLayer.shadowOffset = CGSizeZero
        borderLayer.borderWidth = borderThickness
        borderLayer.shadowColor = textColor?.CGColor
        borderLayer.shadowOpacity = 0.5
        borderLayer.shadowRadius = 1
    }

```

and then change the border and thickness there

**Comment by raulriera** [comment]
Actually I think they will need to be set as internal instead of private :/

**Comment by Jackson0111** [comment]
Ok, I will try thank you!
