### ISSUE TITLE
Can I customize it somehow to give the Akira a corner radius?

### ISSUE THREAD

**Issue by schoeberlt** [raulriera/TextFieldEffects#49]
It would be very useful, and it would look better in my app if the rectangle would have a corner radius.

**Comment by raulriera** [comment]
Hi @schoeberlt ,

Unfortunately there is no way to do it using the customisable options of the effect. You can always just drop the .swift file into your product and tweak it.

**Comment by raulriera** [comment]
Maybe I should expose a bit more properties so that people can tweak them at will...

**Comment by schoeberlt** [comment]
Hi,
I've just closed the issue because I could tweak it. I wrote before I started to think, sorry.
Anyway, great textfields, it made my app beautiful!

**Comment by raulriera** [comment]
Thanks! feel free to share the app when it's done :)

**Comment by schoeberlt** [comment]
It is a long ahead of me, but I'll share it when I am done :)
