### ISSUE TITLE
'x' cannot be contructed because it has no accessible initializers

### ISSUE THREAD

**Issue by samuelbeek** [raulriera/TextFieldEffects#5]
I can't create any textfields (programmatically), for it says that it has no accessible initializers. I think that's weird, since all the textfields are a subclass of UITextField. 

Anyone an idea how to solve this? 
![schermafbeelding 2015-03-05 om 09 46 37](https://cloud.githubusercontent.com/assets/248098/6501764/b7bc0818-c31c-11e4-8a46-88b60a351b9d.png)

**Comment by raulriera** [comment]
Hmmmm apparently there is something really strange going on here. If you download the demo project everything works fine in there. but if you move the source code into another project then you can't use them by code like your example (but you can via Storyboard)

Yet, if you download the framework itself (via Carthage or something, you CAN use it by code but not on Storyboard) I will try to see what's not configured correctly

**Comment by samuelbeek** [comment]
Were in the project is the .framework located? I can't seem to find it. Maybe that's the problem?

**Comment by raulriera** [comment]
You need to build it from the target

**Comment by raulriera** [comment]
Fixed in the latest commit
