### ISSUE TITLE
Xcode 7 Interface Builder problem

### ISSUE THREAD

**Issue by tosbaha** [raulriera/TextFieldEffects#50]
I installed TextFieldEffects with Carthage. I added frameworks and set the custom class for textfield. However XCode doesn't show IBDesignable properties.

![screen shot 2016-02-03 at 14 13 40](https://cloud.githubusercontent.com/assets/971530/12781975/9882f440-ca80-11e5-857d-daedba10416a.png)
![screen shot 2016-02-03 at 14 14 01](https://cloud.githubusercontent.com/assets/971530/12781974/987ca162-ca80-11e5-98a1-d215b2e90fb7.png)
![screen shot 2016-02-03 at 14 14 16](https://cloud.githubusercontent.com/assets/971530/12781973/987b3886-ca80-11e5-8590-d56e6377fb1c.png)

**Comment by raulriera** [comment]
Hi, yeah this is a limitation of .framework files that contains IBDesiganble and IBInspectables. It is mentioned in the README file, I also submitted a ticket to Apple about this a year ago, but looks like no luck.
