### ISSUE TITLE
becomeFirstResponder bug

### ISSUE THREAD

**Issue by sajayshah** [raulriera/TextFieldEffects#51]
http://gfycat.com/ThriftyPiercingAlleycat

The link above describes the issue I'm having when I set the textfield to become the first responder. The animation makes the placeholder to go a little diagonal instead of straight up. Any help would be appreciated. Thanks for making this awesome library.

**Comment by raulriera** [comment]
Hi,

Could you share some code?

**Comment by sajayshah** [comment]
`-(void)viewWillAppear:(BOOL)animated{
    
    [super viewWillAppear:animated];
    
    [self.titleTextField becomeFirstResponder];
}
`

Honestly man that's it. If I comment the becomeFirstResponder part out, the issue doesn't occur. The view was built through the xib file in interface builder. No constraints, since the view is same size no matter the device. Now the most interesting part is when I launch the app through Xcode on iOS simulator it doesn't occur during debug session (when the stop button is active in Xcode), but if I launch without debug session (stop button is not active), then it occurs. Let me know if you were looking for more specifics.

**Comment by raulriera** [comment]
Thanks, will look into it... Yeah I just wanted to know how to reproduce it, from the GIF I though you were just clicking it

**Comment by raulriera** [comment]
I am unable to recreated in the example projected included with the library, does this problem only occurs in the` viewWillAppear:`? If so, do you really want it there? I think `viewDidAppear:` would be a more appropriate place.

**Comment by sajayshah** [comment]
Yes placing it in `viewDidAppear:` fixed the issue. Thank you so much!
