### ISSUE TITLE
HoshiTextField Does not Display Line

### ISSUE THREAD

**Issue by dannybess** [raulriera/TextFieldEffects#53]
As the title suggests, I cannot see the line underneath the Hoshi Text Field. 
Code:

```
let textField = HoshiTextField(frame: textFieldFrame)
textField.delegate = self
textField.placeholderColor = UIColor.whiteColor()
textField.placeholder = "Email"
textField.textColor` = `UIColor.whiteColor()

```

**Comment by raulriera** [comment]
Can you share the whole code and the output as a screenshot?

**Comment by dannybess** [comment]
Hi, 

I actually fixed the problem - forgot to set the borderActiveColor property. However, one more question; 
http://prntscr.com/a397ob
(Screenshot attached)
Is there anyway to increase the distance between the placeholder text and the line, when it is in the inactive state?

**Comment by raulriera** [comment]
Hi,

Not at the moment, you would have to either reduce the size of the font or subclass Hoshi and change the `animateViewsForTextEntry` and `animateViewsForTextDisplay`

**Comment by dannybess** [comment]
Is there anyway to edit the line thickness?

**Comment by raulriera** [comment]
Not on that effect, if you check all the properties in https://github.com/raulriera/TextFieldEffects/blob/master/TextFieldEffects/TextFieldEffects/HoshiTextField.swift you will be able to see what can be changed or not. 

Although, you can always just drop that file and TextFieldEffects.swift into your project and edit the source code to your needs. But some of the effects have hardcoded values to match the originals.
