### ISSUE TITLE
Add more customisation options

### ISSUE THREAD

**Issue by raulriera** [raulriera/TextFieldEffects#54]
Arguably, all the properties should either be customisable or internal so they can be subclassed... Maybe?

**Comment by spotby** [comment]
ideally, I'd love to be able to set the non-active border color from the interface builder!

**Comment by raulriera** [comment]
For which effect? some of them have this option right?

**Comment by Jamonek** [comment]
Yes, they do.

**Comment by tapizquent** [comment]
How would I be able to change the corner radius of the textfields?

**Comment by raulriera** [comment]
> How would I be able to change the corner radius of the textfields?

Depends on the effect, but most likely you will need to subclass them just use the file directly... as this ticket suggests there are no customization options for the layers

**Comment by tapizquent** [comment]
Any way i can round the edges of the textFields?

**Comment by raulriera** [comment]
> Any way i can round the edges of the textFields?

Depends on the effect, but most likely you will need to subclass them just use the file directly... as this ticket suggests there are no customization options for the layers.

**Comment by oniikal3** [comment]
@raulriera I love AkiraTextField. I tried to make it round by subclass. But it's not work. 
Can you suggests more.

**Comment by oniikal3** [comment]
@raulriera Sorry my bad!. It's work good. I just forgot to set "Clip to Bounds"
