### ISSUE TITLE
The Hoshi textFeild borderInactiveColor don't work

### ISSUE THREAD

**Issue by googlb** [raulriera/TextFieldEffects#55]
The Hoshi textFeild borderInactiveColor not show in Simulator

**Comment by raulriera** [comment]
Hi,

Can you provide more info, code? Seems pretty strange that is not working for you and everyone else does.

**Comment by googlb** [comment]
I see your Gif Demo, Hoshi text field has  attributes borderInactiveColor, borderAcitveColor
I can see text Field has a bottom border is borderInactiveColor in gif demo, when text field is fous on, the bottom border change color, I follow the example set borderInactiveColor is gray, borderActiveColor is red and run the demo in ios Simulator ,I can't see the gray border In the default state,I don't know what's wrong.
excuse my poor English.

**Comment by raulriera** [comment]
Can you post a code example? If you use the example project, is it still broken?

**Comment by googlb** [comment]
Hi, I post my code example at this [https://github.com/googlb/TextFieldEffectsTest.git](url)

**Comment by raulriera** [comment]
Hi,

I don't understand hte problem, I ran your project and the borders show fine. Attaching screenshot

<img width="374" alt="screen shot 2016-02-18 at 10 06 18 am" src="https://cloud.githubusercontent.com/assets/24159/13147568/6074d2f0-d627-11e5-9a6b-4d988f6214d9.png">

**Comment by googlb** [comment]
Hi,
I'm sorry ,It's my mistake,In order to be able to view the full screen of Simulator ,I set Simulator Scale 50%, so the borders don't show.I reset scale to 75%,the borders show fine.
Scale 50%
![snip20160219_2](https://cloud.githubusercontent.com/assets/2196880/13165037/868d8f18-d6f4-11e5-8f1b-f4e51b6c0458.png)
Scale 75%
![snip20160219_5](https://cloud.githubusercontent.com/assets/2196880/13165361/dad87a62-d6f7-11e5-87df-6ab229e5ab1c.png)

**Comment by raulriera** [comment]
Glad it's sorted out :)
