### ISSUE TITLE
Subclassing causes exc_bad_access 2 when accessing properties

### ISSUE THREAD

**Issue by royherma** [raulriera/TextFieldEffects#56]
Created a simple subclass 
```
import UIKit
import TextFieldEffects

class CLHoshiTextField: HoshiTextField {
	var isFieldValid = false
}
```

And trying to access it:

``` 
@IBOutlet var emailTextField : CLHoshiTextField!
self.emailTextField.text = "someemail@gmail.com"
```

Causes exc_bad_access 2. The outlet itself is not nil, and it initialized, so trying to figure out why this is hapenning...

**Comment by raulriera** [comment]
Hey, did you figured it out?

**Comment by royherma** [comment]
yep, had to delete the class from storyboard and re-assign. Wasn't specifically related to `TextFieldEffects`, thanks though!
