### ISSUE TITLE
textAlignment - mini-visual-bug

### ISSUE THREAD

**Issue by sentiasa** [raulriera/TextFieldEffects#60]
I tried setting `textField.textAlignment = .Center` however there seem to be a little bug.

At first (without typing anything) it doesn't seem centered...
![screen shot 2016-03-15 at 04 45 42](https://cloud.githubusercontent.com/assets/9021386/13766247/e5cd06ac-ea68-11e5-88dd-58bc8e990a23.png)

But as soon as I start typing a letter, it pushes the blue line to center and actually works fine..
![screen shot 2016-03-15 at 04 46 04](https://cloud.githubusercontent.com/assets/9021386/13766249/e74aa20a-ea68-11e5-86a4-fe56db1a08f6.png)

It's just a mini-visual bug. Everything works nicely after I start typing. Or maybe am I the one breaking it?

**Comment by raulriera** [comment]
No, sadly this a known bug, `textField.textAlignment = .Center` is kind of broken right now on the fields

**Comment by raulriera** [comment]
Closing as this is exactly how UITextField works
