### ISSUE TITLE
Phone Number Formatting with TextFieldEffects | Not an Issue

### ISSUE THREAD

**Issue by sentiasa** [raulriera/TextFieldEffects#61]
I really like TextFieldEffects and I thought that would be awesome to be able to use it with phone number formatter as the user types in. I found [PhoneNumberKit](https://github.com/marmelroy/PhoneNumberKit), which seemed interesting for playing with phone numbers. 

However, when I tried implementing it, I realised that I need to declare it as  `let textField = PhoneNumberTextField()` but I declare my UITextField with `var textField = HoshiTextField()`.

I went into TextFieldEffects.swift and found UITextField there, but changing it there doesn't seem like an option. (I think I should use a delegate to observe every change on the HoshiTextField, but I got very confused)

Can you please guide me on that? Also, please let me know if there are better ways than this for doing it.

**Comment by raulriera** [comment]
If that library is also a subclass of textfield, then yeah it's going to e a problem. You will ace to subclass either one with the other. I would suggest just updating the textfield content (this library) with the output of PhoneNumberKit. UITextFieldDelegate is your friend here

**Comment by sentiasa** [comment]
That's right. I realised I can use UITextFieldDelegate and `shouldChangeCharactersInRange` to achieve it. Thanks a lot!

**Comment by raulriera** [comment]
Glad you sorted it out 😬
