### ISSUE TITLE
Using with prefixed attributedText (as the first character)

### ISSUE THREAD

**Issue by sentiasa** [raulriera/TextFieldEffects#63]
I tried to add a prefixed character as first character ("+" sign for phone numbers) as soon as clicked on the text field by using attributedText. However, it eliminated the creation animation.

To be exact:
1. UITextField is empty
2. As soon as clicked on the text field, + sign added (no animation occured)
3. If clicked outside & empty, delete prefixed + sign (animation occurs)

I am adding the prefixed character in:
```
    func textFieldDidBeginEditing(textField: UITextField) {
        if textField == phoneField {
            if textField.text?.characters.count < 2 {
                makePrefix()
            }
        }
    }
```

Is there a way to check if the animation is completed, and then add the prefixed character? What is the best place to put the creating the attributed text?

**Comment by raulriera** [comment]
I don't know, I haven't try this myself yet. Sadly, at the moment there are no callbacks for the animations

**Comment by sentiasa** [comment]
@raulriera I really like your library, that's why I keep bugging you up. Thanks again!

**Comment by raulriera** [comment]
thanks! and no prob 😄 that's what i am here for
