### ISSUE TITLE
Increasing Height & BorderSize of AkiraTextField

### ISSUE THREAD

**Issue by sentiasa** [raulriera/TextFieldEffects#64]
I am using AkiraTextField and I am trying to

1) Increase the height of the box.. I tried adding `+20` to height, but bottom of the box disappears like this:
![screen shot 2016-03-18 at 04 41 57](https://cloud.githubusercontent.com/assets/9021386/13867029/c7374146-ecc3-11e5-99f7-76b77a8664ea.png)

    private func rectForBounds(bounds: CGRect) -> CGRect {
        return CGRect(x: bounds.origin.x, y: bounds.origin.y + placeholderHeight, width: bounds.size.width, height: (bounds.size.height - placeholderHeight)+20)
    }

2) I tried increasing the border of the box a little bit.. I played with borderSize, but unfortunately, seem like it's kind of buggy. 
`private let borderSize : (active: CGFloat, inactive: CGFloat) = (1.1, 1.1)`

-----
Are there any ways to increase the height or the borderSize? Thanks

**Comment by raulriera** [comment]
What happens when you just increase the size of the overall frame? AkiraTextField(frame: your bigger height) ?
