### ISSUE TITLE
Expected ',' separator AND Expected expression in list of expressions during build

### ISSUE THREAD

**Issue by kishykumar** [raulriera/TextFieldEffects#68]
I am getting the following errors when I tried to build the Pod on Swift version 2.1.1 and Xcode 7.2.

`Expected expression in list of expressions`
`Expected ',' separator`

The errors are on the following lines in file TextFieldEffects.swift:

`fatalError("\(#function) must be overridden")`
and 
`..addObserver(self, selector: #selector(textFieldDidEndEditing)..`

This problem appears to be due to the usage of hashes (#) in the code. 
Any idea what is happening?

**Comment by raulriera** [comment]
You are using the latest version of the library which is only swift 2.2 compatible. You will have to select a lower version to use swift 2.1

**Comment by kishykumar** [comment]
Thanks. Can you please mention which version to use in case anybody else hits it?

**Comment by raulriera** [comment]
Of course, if you look into the [CHANGELOG](https://github.com/raulriera/TextFieldEffects/blob/master/CHANGELOG.md) file, I always mention the compatibility versions in them.

**Comment by jayrav13** [comment]
Appreciate this - it helped me today. Thank you!
