### ISSUE TITLE
Text partially hidden when increasing size with Interface Builder

### ISSUE THREAD

**Issue by oridahan6** [raulriera/TextFieldEffects#72]
Hello,

The text is hidden under the border, when I increase the font size:

<img width="252" alt="screen shot 2016-04-27 at 19 11 36" src="https://cloud.githubusercontent.com/assets/14774991/14859225/e1ed2034-0cab-11e6-9128-2978f5a76e90.png">

I'm using HoshiTextField.

Am I missing something? Is It a known bug?

Thanks,
Ori.

**Comment by raulriera** [comment]
Hi,

Yeah it's a bit tricky, because not any font size will work with any "text field" size... You will have to choose something that works nicely with the 2 options.

**Comment by rcchen** [comment]
I've actually found it pretty useful to set some default text when laying this out in IB so it shows up in the preview.

![image](https://cloud.githubusercontent.com/assets/1175041/15094794/80d61704-1464-11e6-828c-8c764c869072.png)

![image](https://cloud.githubusercontent.com/assets/1175041/15094795/83835f84-1464-11e6-9a2d-e9070d9c5e92.png)

**Comment by antonioreyna** [comment]
I am having a similar problem but on runtime, when i set a text in the viewdidload to the field the placeholder cuts off.

<img width="198" alt="captura de pantalla 2016-08-16 a las 4 39 08 p m" src="https://cloud.githubusercontent.com/assets/147514/17716953/b4db51f2-63d0-11e6-9a55-836fb234fb16.png">

If i load it empty then write, the text at the bottom sets correctly.

**Comment by raulriera** [comment]
Try different heights, sadly it won't work with small fields. Some effects require a reasonable height size

**Comment by antonioreyna** [comment]
I keep increasing the size and apparently what gets bigger is just the text field area not the label

**Comment by raulriera** [comment]
I'm not ting about the font size, Are you making the whole view bigger?

**Comment by antonioreyna** [comment]
I am setting the height constraint of the field at the moment in 48 not the font size, the height, and i havent set the label scale

**Comment by raulriera** [comment]
And there is no number that makes them both appear correctly?

**Comment by antonioreyna** [comment]
no, i tried some and none gives the correct result.

**Comment by raulriera** [comment]
In that case, can you please create a project that reproduces the problem? I ask this before the values on the sample project seem to work correctly (but maybe that is too tall for your UI)

**Comment by antonioreyna** [comment]
I am using autolayout, could that be the problem?

**Comment by raulriera** [comment]
So am I :)

**Comment by antonioreyna** [comment]
look, it looks fine on the ib,

<img width="377" alt="captura de pantalla 2016-08-18 a las 9 16 55 a m" src="https://cloud.githubusercontent.com/assets/147514/17777046/9cac30ce-6524-11e6-9277-e1e3ac0b1ae6.png">


But on run time when it has data on load.

<img width="406" alt="captura de pantalla 2016-08-18 a las 9 19 15 a m" src="https://cloud.githubusercontent.com/assets/147514/17777101/e0901a76-6524-11e6-9c2b-c93bc8491d31.png">


And when it loads with no data is correct look.

<img width="409" alt="captura de pantalla 2016-08-18 a las 9 19 52 a m" src="https://cloud.githubusercontent.com/assets/147514/17777122/f2e5702c-6524-11e6-9c7d-e87ff0f22e17.png">


there are my settings:

<img width="286" alt="captura de pantalla 2016-08-18 a las 9 18 31 a m" src="https://cloud.githubusercontent.com/assets/147514/17777131/fb3bd054-6524-11e6-8fbc-37ca20319a25.png">

**Comment by antonioreyna** [comment]
look, it looks fine on the ib,

<img width="377" alt="captura de pantalla 2016-08-18 a las 9 16 55 a m" src="https://cloud.githubusercontent.com/assets/147514/17777046/9cac30ce-6524-11e6-9277-e1e3ac0b1ae6.png">


But on run time when it has data on load.

<img width="412" alt="captura de pantalla 2016-08-18 a las 9 22 07 a m" src="https://cloud.githubusercontent.com/assets/147514/17777209/41dad500-6525-11e6-97a7-fcb88f2e364f.png">



And when it loads with no data is correct look.

<img width="409" alt="captura de pantalla 2016-08-18 a las 9 19 52 a m" src="https://cloud.githubusercontent.com/assets/147514/17777122/f2e5702c-6524-11e6-9c7d-e87ff0f22e17.png">


there are my settings:

<img width="286" alt="captura de pantalla 2016-08-18 a las 9 18 31 a m" src="https://cloud.githubusercontent.com/assets/147514/17777131/fb3bd054-6524-11e6-8fbc-37ca20319a25.png">

**Comment by antonioreyna** [comment]
And when i load it with no data, and then write data, everything is fine.

**Comment by antonioreyna** [comment]
As you can see when it has data on viewDid load the space between the label and the line is bigger than on an empty  field

**Comment by raulriera** [comment]
The line is bigger on Hoshi, that is how it works. Make your your AutoLayout is not shrinking the textfield (given that is squished between 2 constraints)

If you can setup a sample project it would be better to debug. But I believe is the size getting smaller than the effect allows.

**Comment by antonioreyna** [comment]
I unchecked adjust to fit on the textfield but same result 

<img width="211" alt="captura de pantalla 2016-08-18 a las 9 29 29 a m" src="https://cloud.githubusercontent.com/assets/147514/17777486/572df6a2-6526-11e6-8035-5043cf7b41f7.png">

But do you see on the previous images, the margin between the line and the label "Nombre completo" is bigger when you fill the textfield on viewdidload than when it starts empty:

Non empty viewDidLoad.

<img width="80" alt="captura de pantalla 2016-08-18 a las 9 31 03 a m" src="https://cloud.githubusercontent.com/assets/147514/17777534/863e9e4c-6526-11e6-9983-be975032b1be.png">

Empty:

<img width="135" alt="captura de pantalla 2016-08-18 a las 9 31 42 a m" src="https://cloud.githubusercontent.com/assets/147514/17777559/97302874-6526-11e6-94e6-450a7aa3c48a.png">

Both on same run, so dont think i recompile it

**Comment by antonioreyna** [comment]
Fixed it, as you mentioned it was a problem at my end I am so sorry for all the problems dude!! thank you for your support.

I had a different minFont which was bigger than the font size lets say in my font size was set to 16 and the min font size at 17.

Thanks again.
