### ISSUE TITLE
Hoshi Border Inactive Color doesnt get applied

### ISSUE THREAD

**Issue by smarques84** [raulriera/TextFieldEffects#73]
I am trying your library on Xcode 7.3 with iOS9 simulator and somehow even if i copy an Hoshi Text Field from your example to another View Controller the border inactive color doesn't show up. Strange is it works fine on your table view controller example. 

I tried to check every setting on the hoshi text field but didn't noticed anything different could you please check whats going on?

Great library by the way!

**Comment by raulriera** [comment]
Hi,

Could you provide an example project? It sounds like you are missing something

**Comment by smarques84** [comment]
I just added a new view controller with hoshi text field to your project where the red border inactive doesn't show up. I even copied the working one from your table view controller but the copy doesn't work.

Let me know what i am doing wrong

Best Regards
Stéphane

[TextFieldEffects.zip](https://github.com/raulriera/TextFieldEffects/files/275909/TextFieldEffects.zip)

**Comment by raulriera** [comment]
Mmmm seems to be working for me, is this what you expect to see?

![simulator screen shot 21 may 2016 16 14 30](https://cloud.githubusercontent.com/assets/24159/15449210/2c0cd4c2-1f6f-11e6-9779-7674c8eb473e.png)

**Comment by raulriera** [comment]
Make sure your zoom level is 100% ;)

**Comment by smarques84** [comment]
Oh man that was it!  👍 The zoom level was 50% to fit my macbook pro screen ahhh.. cant believe i wasted hours on this the thing.The funny thing was it was showing correctly on your table view controler so i thought it was something with the configuration of the hoshi text field.

Thanks for you support and have a great weekend 👍 

Best Regards
Stéphane

**Comment by raulriera** [comment]
Hehe this happened to me once with the UITableView separators 😬

Thanks for using the libraries! have a good weekend as well
