### ISSUE TITLE
not responding to textFieldShouldReturn

### ISSUE THREAD

**Issue by LiveRock** [raulriera/TextFieldEffects#74]
What should I do to capture textFieldShouldReturn protocol/delegate?

**Comment by raulriera** [comment]
Hi,

Could you be more specific? Sample code, sample project, etc? this works fine in the example project attached to this library

<img width="543" alt="screen shot 2016-05-30 at 11 47 58" src="https://cloud.githubusercontent.com/assets/24159/15647583/60dd9f08-265c-11e6-8e86-735ab11451f4.png">

**Comment by LiveRock** [comment]
![image](https://cloud.githubusercontent.com/assets/211891/15649480/7b1818e2-26a4-11e6-9bf6-4dc73e896c00.png)

**Comment by LiveRock** [comment]
I am not getting the print line or any action within the func

**Comment by raulriera** [comment]
As you can see from my screenshot, the debugger stopped there without any problems. Are you sure you are setting the delegate correctly?

**Comment by raulriera** [comment]
that won't assign it as a delegate though, you need to `textField.delegate = self` if you want your View Controller to be the delegate of the given textfield

**Comment by LiveRock** [comment]
Ok, you are right! Thank you so much!

**Comment by raulriera** [comment]
👍
