### ISSUE TITLE
Cannot change active border color while editing

### ISSUE THREAD

**Issue by fruitcoder** [raulriera/TextFieldEffects#75]
I wanted to use the active border color of a HoshiTextFied to indicate the valid number of characters. Unfortunately, when I try to set the activeBorderColor to another color during editing it just gets the inactive border color until I resign first responder. 
I noticed the implementation of updateBorder() and changed it to the following:

```
inactiveBorderLayer.frame = rectForBorder(borderThickness.inactive, isFilled: text!.isEmpty)
inactiveBorderLayer.backgroundColor = borderInactiveColor?.CGColor

activeBorderLayer.frame = rectForBorder(borderThickness.active, isFilled: text!.isNotEmpty)
activeBorderLayer.backgroundColor = borderActiveColor?.CGColor
```

I don't know if the current implementation matches the expectations.

**Comment by raulriera** [comment]
Hi,

Maybe a simpler solution would be to allow access to more objects and have less things be private. That way you could subclass and do whatever you want to the layers and functions.

Those changes seem fine, only problem would be the `!` and no't too sure what will happen if you rotate your device while editing

**Comment by fruitcoder** [comment]
Yeah I first tried to subclass, but the private method declaration didn't let me :)

for safety I now use 
```
inactiveBorderLayer.frame = rectForBorder(borderThickness.inactive, isFilled: text?.isEmpty ?? true)
inactiveBorderLayer.backgroundColor = borderInactiveColor?.CGColor
        
activeBorderLayer.frame = rectForBorder(borderThickness.active, isFilled: text?.isNotEmpty ?? false)
activeBorderLayer.backgroundColor = borderActiveColor?.CGColor
```

because if the text is nil it should definitely not be in an active state.

**Comment by raulriera** [comment]
That looks good 👍
