### ISSUE TITLE
Yoshiko textfield's attributes are being ignored

### ISSUE THREAD

**Issue by Sweeper777** [raulriera/TextFieldEffects#76]
I am using Xcode 7.3 the interface builder to put Yoshiko textfields in table view cells. And then Xcode shows this warning:

> warning: IB Designables: Ignoring user defined runtime attribute for key path "activeBorderColor" on instance of "UITextField". Hit an exception when attempting to set its value: [<UITextField 0x7f9ae3c66d80> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key activeBorderColor.

Also, it says that the class `YoshikoTextField` does not exist! But it _must_ exist since I can refer to it in my code by `import TextFieldEffects`! What should I do?

**Comment by raulriera** [comment]
Hey, did you set the module as well? When setting the subclass in Interface Builder, you also need to specify the module (the name of the library)

**Comment by Sweeper777** [comment]
Oh I see! It's working now. Thank you! It's weird that I don't have to set  the  module when I was using other cocoapods.
