### ISSUE TITLE
Cannot use custom Color (with red, green, blue initializer) on inactive and active border

### ISSUE THREAD

**Issue by MathisDetourbet** [raulriera/TextFieldEffects#77]
Hi ! 

First of all, thanks for your awesome textfield effect. Nice job !

But I found an issue... When I want to programmatically change the border color with the custom UIColor class initializer, the textfield border color is white.. I'm using the code below to change the border color :
`self.passwordTextField.borderActiveColor = UIColor(red: 72, green: 165, blue: 255, alpha: 1)
self.passwordTextField.borderInactiveColor = UIColor(red: 72, green: 165, blue: 255, alpha: 1)`

What is wrong ?
Thanks for your help.

**Comment by raulriera** [comment]
Hi, that is not how you set the colors in iOS, those values go from 0 to 1. This will point you to the right direction https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIColor_Class/#//apple_ref/occ/instm/UIColor/initWithRed:green:blue:alpha:

**Comment by MathisDetourbet** [comment]
Oups.. I did not see the documentation because I was so convinced of my code... 

So thank you for your help ! And sorry for the disruption

**Comment by raulriera** [comment]
No prob :) this got me as well at one point
