### ISSUE TITLE
erro unwrapped

### ISSUE THREAD

**Issue by renatords** [raulriera/TextFieldEffects#80]
Hi. I install TextFieldEffects in my Xcode 7.3.1 and recive a error about  unwrapped in all classes. Tks
Apple Swift version 2.2 (swiftlang-703.0.18.8 clang-703.0.31)

**Comment by raulriera** [comment]
Hi,

Can you supply more information please?

**Comment by renatords** [comment]
Hi, sure.
I configured my por file 
use_frameworks!
pod 'TextFieldEffects' and installed correctly. But when I opened my project and builded KaedeTextField, IsaoTextField and orthers show error like this:
"... Value of optional type 'UIFont?' not unwrapped; did you mean to use '!' or '?'? "
"...Value of optional type 'String?' not unwrapped; did you mean to use '!' or '?'?"
Do you need any more information?
Thanks

**Comment by raulriera** [comment]
Sorry I don't think this is helping me either. Do you see the problem when you download the example project yourself?

**Comment by renatords** [comment]
No. Now I tested the 1.1.1 tag adding to the project without using the pod and it worked. My target is to 7.1

**Comment by raulriera** [comment]
Your iOS target is set to 7? I don't think that is supported. I started this for iOS 8 and above

**Comment by renatords** [comment]
Thank you very much. Sorry to bother you

**Comment by raulriera** [comment]
No problem at all, I hope you can get it sorted out soon :(
