### ISSUE TITLE
Facing Problem while trying to include in XCode 7.0

### ISSUE THREAD

**Issue by anandramv** [raulriera/TextFieldEffects#81]
getting compilation errors while trying to compile the project in Xcode 7.0. Kindly help to resolve this issue

**Comment by raulriera** [comment]
Hi,

I am going to need way more info than that :/

**Comment by diegojmaldonado** [comment]
When i downloaded the project (from master) and execute it on XCode 7.3.1 I received the following message:
![errormessage](https://cloud.githubusercontent.com/assets/2761838/16822797/7eda690e-4935-11e6-8327-354df8aa9c40.png)

So, maybe anandramv is facing the same issue. 
@anandramv , if you do not want to upgrade your XCode version (yet) maybe you can try to compile the source code located at: https://github.com/raulriera/TextFieldEffects/releases/tag/1.2.0

@raulriera I just came across with your work but seems great, thanks and keep it up!

**Comment by raulriera** [comment]
Yeah, the current code in `master` is just the stepping stone to Swift 3 when it's officially supported.

Thanks for the kind words :)

**Comment by anandramv** [comment]
@diegojmaldonado  @raulriera  thank you very much for the info. I was downloading from the Git directly and using it. Will check for the branch and will use the same. 
Really appreciate your help.

@raulriera The component is really cool! Keep creating more!!  👍
