### ISSUE TITLE
UITextField leftView/rightView support

### ISSUE THREAD

**Issue by yberdnikov** [raulriera/TextFieldEffects#82]
Right now framework ignores left/right views of UITextField while calculates size and position in `editingRectForBounds` and `textRectForBounds` methods.
Here's possible solution:

```
    var rect = CGRectOffset(bounds, textFieldInsets.x, textFieldInsets.y)
    rect.size.width -= (self.rightView?.bounds.size.width ?? 0)
```

However, also need to take into account left/right views modes.

**Comment by AbdallahJaja** [comment]
where to write this code ?

**Comment by yberdnikov** [comment]
in `editingRectForBounds` and `textRectForBounds` methods.
