### ISSUE TITLE
Getting various error on Yoshiko and Akira

### ISSUE THREAD

**Issue by vinamelody** [raulriera/TextFieldEffects#83]
Hi, I tried downloading the latest and branch tag 1.20 and getting these errors. Please help :)
Thanks a lot!

![screenshot_230](https://cloud.githubusercontent.com/assets/990511/17059920/0ffabc74-505a-11e6-96e9-b1044d2817cc.png)

**Comment by raulriera** [comment]
Hi,

All your errors are because of Swift 3, are you sure you downloaded the 1.2 tag?

**Comment by vinamelody** [comment]
Yup, downloaded from https://github.com/raulriera/TextFieldEffects/releases/tag/1.2.0
my Apple Swift version 2.2 (swiftlang-703.0.18.8 clang-703.0.31)

**Comment by raulriera** [comment]
Did you ever downloaded the Swift 3 version? Because all those errors are actual Swift 3 code examples (you can tell by the missing `Color` and `lower case enums like cgColor`. Try doing a clean build or clearing the derived data

**Comment by raulriera** [comment]
I just downloaded https://github.com/raulriera/TextFieldEffects/releases/tag/1.2.0 and I can build it without errors with Xcode 7...

**Comment by vinamelody** [comment]
Didn't download Swift 3 version but turns out that I needed to do Clean and Build again.
oh and I tried installing using pods, so i removed that too!
Thanks a lot for your help!
