### ISSUE TITLE
Round Edges

### ISSUE THREAD

**Issue by rmickeyd** [raulriera/TextFieldEffects#84]
I am using Jiro and need some help rounding edges.  Any ideas?
![img_0932](https://cloud.githubusercontent.com/assets/11418552/17073483/fd4cbb24-5025-11e6-8e29-b50bdd440e6e.jpg)

**Comment by raulriera** [comment]
You will need to edit the library itself, you are just rounding the corners of the TextField (the textfield is everything, the box where you enter the text and the placeholder label that moves around)

You need to set the rounding corners to the little white box, I suggest you start by looking at these two methods

```
// MARK: - Overrides
            
    override public func editingRect(forBounds bounds: CGRect) -> CGRect {
        return bounds.offsetBy(dx: textFieldInsets.x, dy: textFieldInsets.y)
    }
    
    override public func textRect(forBounds bounds: CGRect) -> CGRect {
        return bounds.offsetBy(dx: textFieldInsets.x, dy: textFieldInsets.y)
    }
```
