### ISSUE TITLE
HoshiTextfield's messup when any alert view appear.

### ISSUE THREAD

**Issue by Filipetb** [raulriera/TextFieldEffects#88]
The textfield is working like a charm until an UIAlertController appear :(

I put some HoshiTextField's in different cell's of a tableview.
I am using Xcode 7.3.1 with swift 2.3.

Look the images:
![whatsapp image 2016-08-30 at 20 41 12](https://cloud.githubusercontent.com/assets/4166843/18111279/a3e196f2-6ef4-11e6-8f85-2f2036cd2112.jpeg)
![whatsapp image 2016-08-30 at 20 56 47](https://cloud.githubusercontent.com/assets/4166843/18111283/a3e3771a-6ef4-11e6-95c6-46886a185916.jpeg)

**Comment by raulriera** [comment]
Hi, can you provide a sample project? That looks like something very specific

**Comment by Filipetb** [comment]
Hi, I was not able to reproduce the same issue in a sample project, after that I realize that I forget to add some constraints to the HoshiTF's in my original project. I am sorry for making you worry about it. Thank you for the very fast reply, you did a good job with this files! =D

**Comment by raulriera** [comment]
Glad you worked it out 💃

**Comment by ndduong97** [comment]
I am facing the same problems. @Filipetb Do you remember what constraints you added? I do have a height constraint so I am not sure what the problem is. 

This only happens when the text field is selected and then I switch to a different app and then switch back again.

**Comment by raulriera** [comment]
Hey @ndduong97, if you could provide some code I can help you debug

**Comment by ndduong97** [comment]
Sure, this is how my text field is set up in the storyboard.

<img width="446" alt="screen shot 2017-06-06 at 4 39 46 pm" src="https://cloud.githubusercontent.com/assets/15851465/26823199/fab5bb48-4ad6-11e7-9b64-cbae25899d65.png">

I tried adding a constraint to fix the height but it still doesn't work. I tried making the text field bigger as well but the space only gets bigger and it doesn't actually fit the text.

<img width="243" alt="screen shot 2017-06-06 at 4 39 32 pm" src="https://cloud.githubusercontent.com/assets/15851465/26823211/0868f23c-4ad7-11e7-89dd-7b61e3edac88.png">

<img width="249" alt="screen shot 2017-06-06 at 4 41 13 pm" src="https://cloud.githubusercontent.com/assets/15851465/26823298/540f96e6-4ad7-11e7-8619-5ff4eb6565fd.png">
This only happens after the text field is currently selected (as in the keyboard is shown), then I switch to another app and then switch back to it. 

![img_5977](https://cloud.githubusercontent.com/assets/15851465/26823294/4cbd70ca-4ad7-11e7-9022-e82835bb8cce.PNG)

Thanks in advance for your help!

**Comment by raulriera** [comment]
You have too many constraints in your textfield and you are missing the trailing one so it doesn't move to the left like you see in your screenshots. Try removing the centre X and Y ones and adding a trailing constraint

**Comment by ndduong97** [comment]
Thanks for the quick reply! I did try doing that and it didn't fix the problem. Even without any constraints, the text still gets covered so I think it might be something to do with the text field?

**Comment by raulriera** [comment]
Does this happen in the sample project as well?
