### ISSUE TITLE
Hint Text doesn't go up again when using shouldChangeCharactersInRange

### ISSUE THREAD

**Issue by niennonno** [raulriera/TextFieldEffects#89]
When overriding the textField delegate function shouldChangeCharactersInRange with the HoshiTextField, when we delete some text and start typing again, the text overlaps the hint text as it doesn't go up. Is there a way to fix that?

**Comment by raulriera** [comment]
Can you provide more info on the issue? Code would be nice

**Comment by Cokile** [comment]
A capture of the issue is also appreciated.
