### ISSUE TITLE
IBDesignable build errors even in the DEMO project.

### ISSUE THREAD

**Issue by realq86** [raulriera/TextFieldEffects#90]
Hi,

I've been trying to integrate this framework into my Objc/Swift project without luck using xCode 7.3.1 
I then proceed to build the DEMO project and getting the same error.  They are mostly around the IBDesignable tag with missing ";" and "Expected Declaration" errors.  I see this project have not be updated sometime now, does this have something to do with it?

**Comment by raulriera** [comment]
the master branch is Swift 3.0, which is only Xcode 8. Please try one of the tagged versions https://github.com/raulriera/TextFieldEffects/releases

**Comment by realq86** [comment]
Thanks @raulriera for the quick reply!!  Now I feel really stupid!

**Comment by raulriera** [comment]
no prob :) the repo could be more obvious about it as well

**Comment by realq86** [comment]
I don't have the version # of Swift memorized, so did not realized it requires xCode8.
