### ISSUE TITLE
Support Swift 3

### ISSUE THREAD

**Issue by lsalinaszam** [raulriera/TextFieldEffects#92]
Do you have a branch to support swift 3?

**Comment by Cokile** [comment]
From the commit records, you could see that the master branch do support swift3

**Comment by raulriera** [comment]
I just tagged 1.3.0 as Swift 3 support :) sadly I don't know whata is happening to cocoapods and I'm getting stucked here 

```
[!] Found podspec `TextFieldEffects.podspec`
Updating spec repo `master`
```
