### ISSUE TITLE
xCode 8 GM and Swift 3

### ISSUE THREAD

**Issue by justdan0227** [raulriera/TextFieldEffects#93]
Any update for xCode8 and Swift 3?

**Comment by raulriera** [comment]
The latest release its Xcode 8¡ swift 3.. there is no cocoa pods though. I can't get it to push to trunk

**Comment by DiegoRenau** [comment]
Hi Raul, could you push it?  
I m having some problems with the storyboard. The autolayout throw some errors. I supose that with this release this will be is fixed and I would like to test it.
Thanks!

**Comment by raulriera** [comment]
It's not on cocoapods yet, but you can always just point cocoapods to a commit message (the 1.3.0 release for example)

**Comment by raulriera** [comment]
Cocoapods keeps erroring on `Encountered an unknown error (Simulator iPhone 4s is not available.)` when trying to push trunk

**Comment by XOneto9** [comment]
Ok, I have read all of your answers, It is a little sad having a terrible unknown error.
Maybe, is it more long time to release???

**Comment by Natelegreat1** [comment]
For anyone else who needs to use the latest tag until cocoa pods is working :)
`    pod 'TextFieldEffects', :git => 'https://github.com/raulriera/TextFieldEffects.git', :tag => '1.3.0'
`

**Comment by raulriera** [comment]
Version 1.3.0 has been pushed to Cocoapods
