### ISSUE TITLE
Unknown class on Xcode 8.0 Swift 3.0

### ISSUE THREAD

**Issue by nhantrivinh** [raulriera/TextFieldEffects#94]
![unknownclass](https://cloud.githubusercontent.com/assets/12175043/18594308/7349fc28-7c69-11e6-9a2a-d32701e4869c.png)

**Comment by raulriera** [comment]
I don't think you need to set the module when using Cocoapods

**Comment by nhantrivinh** [comment]
![sameissue](https://cloud.githubusercontent.com/assets/12175043/18595077/5065f456-7c6d-11e6-945b-54acf106219a.png)

I tried without TextFieldEffects and with it. Hmm...

**Comment by raulriera** [comment]
That is another error, not all the textfield have the same properties, you didn't change the ones you selected

**Comment by nhantrivinh** [comment]
Even after deleting all the user attributes and changing the inspector same problem

**Comment by raulriera** [comment]
Don't know what else to say, this doesn;t happen in the sample project. Can you provide a minimal project with the problem getting reproduced?

**Comment by nhantrivinh** [comment]
Ok, so setting the Class from cocoapods doesn't work, but by dragging the folder into my project does

**Comment by raulriera** [comment]
That is strange though, are you sure the pod is setup correctly?

**Comment by nhantrivinh** [comment]
I used the 1.3.0 release, the only way I got my Xcode 8 Swift 3.0 to work after updating my Xcode

**Comment by raulriera** [comment]
Closing this. If you are able to reproduce it on a project please open it again

**Comment by ytgdoc** [comment]
please fix it for me
Dear raulriera, 
i has to install your lib, but when i use it, i got error in buildtime that:
Failed to render and update auto layout status for ViewController (BYZ-38-t0r): dlopen(TextFieldEffects.framework, 1): no suitable image found.  Did find:
	TextFieldEffects.framework: required code signature missing for 'TextFieldEffects.framework'
thank for support!
