### ISSUE TITLE
IB Designables Error 

### ISSUE THREAD

**Issue by alanshih** [raulriera/TextFieldEffects#96]
I am using xCode 8 with Swift 2.3 so I install TextFieldEffects using Cocoapods
`
pod 'TextFieldEffects', '~> 1.2.0'`

The problem is that I get errors ever since I upgraded to xCode 8 

![screen shot 2016-09-26 at 3 23 40 pm](https://cloud.githubusercontent.com/assets/17047500/18848661/692bba60-83fd-11e6-8c8a-0c9ea3669834.png)

I believe it's because of the `@IBDesignable` notation for the `TextFieldEffects` as it is only throwing errors on views with these custom TextFields.

**Comment by raulriera** [comment]
Hi,

Can you confirm this is due to this library? A sample project would be awesome for testing this

**Comment by datamaru** [comment]
I also encountered this problem but it also occurred when I was using another library that use IBDesignable so I guess the problem is in the XCode itself. I suggest you use XCode 7.3 if you are still developing with Swift 2.3 like me.

**Comment by alanshih** [comment]
@raulriera  
I have attached the error:
Application Specific Information:
```
CoreSimulator 303.8 - Device: IBSimDeviceTypeiPad2x - Runtime: iOS 10.0 (14A345) - DeviceType: IBSimDeviceTypeiPad2x

Dyld Error Message:
  Symbol not found: __TF10Foundation24_convertNSStringToStringFGSqCSo8NSString_SS
  Referenced from: /Users/USER/Library/Developer/Xcode/DerivedData/Rapid-edcohojmdvjelfgoxvgkmwfchzvk/Build/Intermediates/IBDesignables/Products/Debug-iphonesimulator/TextFieldEffects/TextFieldEffects.framework/TextFieldEffects
  Expected in: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Xcode/Overlays/../../../../../../Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator/libswiftFoundation.dylib
```

@datamaru  My computer automatically upgraded me to XCode 8. I don't suppose there is a way to downgrade?

**Comment by datamaru** [comment]
You can download XCode 7.3.dmg at the Apple Developer Download section. Go here https://developer.apple.com/download/ and scroll all the way down to found "See more downloads" button. You can found Xcode 7.3 there.

**Comment by alanshih** [comment]
@raulriera 
Debuged the Yoshiko I am using and it is failing on:

```
private var placeholderHeight : CGFloat {
        return placeHolderInsets.y + placeholderFontFromFontAndPercentageOfOriginalSize(font: font!, percentageOfOriginalSize: placeholderFontScale).lineHeight
    }
    
```

EXC BAD ACCESS

**Comment by raulriera** [comment]
Can you provide a sample project? this error doesn't happen on the Sample project in this library

**Comment by Nallo** [comment]
In my project I get the same error as the one of alanshih. I am using Pods which do not have any `@IBDesignable`.

Trying with an empty `workspace` after getting `TextFieldEffects` using `Pod Install` the error does not show up.

I am guessing, if we import `TextFieldEffects` with drag/drop  the issue should go away (Not tested yet).

**Comment by alanshih** [comment]
@Nallo Do you know of a way to fix it on existing projects that is using pods?

**Comment by Nallo** [comment]
@alanshih I removed from the source of the Pod the string `@IBDesignable`.

In my project I am using only `HoshiTextField` therefore, I looked for the `HoshiTextField.swift` file and I changed the first line of the class from `@IBDesignable public class HoshiTextField: TextFieldEffects {` to `public class HoshiTextField: TextFieldEffects {`.
If you are using other custom textfields you should do the same procedure for each textfield class. After that, clean your project, restart Xcode and perform a full build. The errors should be gone but you won't be able to see anymore the UI updates of the textfields in the Storyboard.

**Comment by alanshih** [comment]
@Nallo That did it :). Thank you. Is this considered a xCode bug that will eventually be fixed one day? I don't really understand the issue.

**Comment by Nallo** [comment]
@alanshih I have no idea whether is a bug in Xcode or in the Pod management. However, you can stay updated by checking this repo updates.

Hope this helps.

**Comment by alanshih** [comment]
@Nallo actually, pulling out the IBDesignable did not fully solve the issue. If I add a new "YoshikoTextField" after removing the `@IBDesignable`, it will not render and throw the same error.

**Comment by Nallo** [comment]
@alanshih my solution was only a **workaround** for my specific case.

If you add a `YoshikoTextField` and you get the error, you need to remove the `@IBDesignable` string from the `YoshikoTextField.swift` file, clean the project, close Xcode and reopen Xcode again.

**Comment by Nathan187** [comment]
Yeah, I really wanted to use this library but it just isn't playing nice in my storyboard and the attributes aren't displaying properly when I try to adjust settings/properties.  Better documentation would have been nice.

**Comment by raulriera** [comment]
Anythign ni particular Nathan? All files hace documentation headers on them. Also, PRs are always  welcomed.

**Comment by Etheleadred** [comment]
When using TextFieldEffects in Xcode 9, it tells me "Designables: Build failed".

**Comment by raulriera** [comment]
Can you provide more info? What version, how did you install it, does it happen in the sample project, etc?

**Comment by Etheleadred** [comment]
I found out that it is a bug in Xcode 9, not in the code...
