### ISSUE TITLE
Wrong position

### ISSUE THREAD

**Issue by cooler333** [raulriera/TextFieldEffects#98]
![screen shot 2016-10-03 at 15 40 21](https://cloud.githubusercontent.com/assets/2772537/19037583/b8546c18-897f-11e6-9d9c-d4cbc6e88777.png)

``` swift
textAlignment = .center
```

**Comment by raulriera** [comment]
Sadly, this is how UITextField works as well

**Comment by raulriera** [comment]
If you remove the subclass you can see it behaving the same

**Comment by cooler333** [comment]
![screen shot 2016-10-03 at 16 39 01](https://cloud.githubusercontent.com/assets/2772537/19039281/f2b6d8c0-8987-11e6-9f6c-0a8a99677358.png)

all is ok

**Comment by Cokile** [comment]
@cooler333  How did you fix that?

**Comment by cooler333** [comment]
```swift
    var _placeholder: String?
    override open var placeholder: String? {
        didSet {
            _placeholder = placeholder
            super.placeholder = ""
            updatePlaceholder()
        }
    }
```

**Comment by cooler333** [comment]
I'll make PR

**Comment by raulriera** [comment]
Should that second screenshot have the underline line? Everything completely black seems like a bug

**Comment by cooler333** [comment]
No, it just UITextField

**Comment by cooler333** [comment]
When pod will be update?

**Comment by raulriera** [comment]
I'll update it tonight, I still need to further test it and replace the comment header on updatePlaceholder that has incorrect information. You can reference the commit if you need it immediately.

**Comment by cooler333** [comment]
thanks! I'll waiting for it!

**Comment by raulriera** [comment]
Thank you for the pull request :)

**Comment by raulriera** [comment]
Maybe I should have tested this before merging. But it seems that all the placeholders are gone now. I am going to revert back to the previous version for the moment

**Comment by cooler333** [comment]
It's ok :)

i've got [fork](https://github.com/cooler333/TextFieldEffects), you could test it. All placeholder in place. And I've also found bug: 

![screen shot 2016-10-04 at 11 20 22](https://cloud.githubusercontent.com/assets/2772537/19066962/9ac975c6-8a24-11e6-9fcb-b3c40497f2d1.png)
